// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const countAccounts = `-- name: CountAccounts :one
SELECT count(*) FROM identity.account
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL OR username_lower LIKE $2 OR lower(email) LIKE $2)
`

type CountAccountsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountAccounts(ctx context.Context, arg CountAccountsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccounts, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO identity.account (username, username_lower, email, status, mc_login_enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, username_lower, email, status, mc_login_enabled, email_verified_at, created_at, updated_at
`

type CreateAccountParams struct {
	Username       string `json:"username"`
	UsernameLower  string `json:"username_lower"`
	Email          string `json:"email"`
	Status         string `json:"status"`
	McLoginEnabled bool   `json:"mc_login_enabled"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (*IdentityAccount, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Username,
		arg.UsernameLower,
		arg.Email,
		arg.Status,
		arg.McLoginEnabled,
	)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameLower,
		&i.Email,
		&i.Status,
		&i.McLoginEnabled,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM identity.account WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, username, username_lower, email, status, mc_login_enabled, email_verified_at, created_at, updated_at FROM identity.account WHERE lower(email) = lower($1)
`

// 邮箱唯一性按 lower(email) 判断(变更 C-10),登录/找回密码都走这里。
func (q *Queries) GetAccountByEmail(ctx context.Context, lower string) (*IdentityAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, lower)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameLower,
		&i.Email,
		&i.Status,
		&i.McLoginEnabled,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, username_lower, email, status, mc_login_enabled, email_verified_at, created_at, updated_at FROM identity.account WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (*IdentityAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameLower,
		&i.Email,
		&i.Status,
		&i.McLoginEnabled,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, username_lower, email, status, mc_login_enabled, email_verified_at, created_at, updated_at FROM identity.account WHERE username_lower = $1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, usernameLower string) (*IdentityAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, usernameLower)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameLower,
		&i.Email,
		&i.Status,
		&i.McLoginEnabled,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, username, username_lower, email, status, mc_login_enabled, email_verified_at, created_at, updated_at FROM identity.account
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL OR username_lower LIKE $2 OR lower(email) LIKE $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAccountsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]*IdentityAccount, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*IdentityAccount{}
	for rows.Next() {
		var i IdentityAccount
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.UsernameLower,
			&i.Email,
			&i.Status,
			&i.McLoginEnabled,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountEmailVerified = `-- name: SetAccountEmailVerified :one
UPDATE identity.account
SET email_verified_at = now(), status = 'active'
WHERE id = $1
RETURNING id, username, username_lower, email, status, mc_login_enabled, email_verified_at, created_at, updated_at
`

func (q *Queries) SetAccountEmailVerified(ctx context.Context, id uuid.UUID) (*IdentityAccount, error) {
	row := q.db.QueryRow(ctx, setAccountEmailVerified, id)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameLower,
		&i.Email,
		&i.Status,
		&i.McLoginEnabled,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const setMCLoginEnabled = `-- name: SetMCLoginEnabled :one
UPDATE identity.account SET mc_login_enabled = $2 WHERE id = $1 RETURNING id, username, username_lower, email, status, mc_login_enabled, email_verified_at, created_at, updated_at
`

type SetMCLoginEnabledParams struct {
	ID             uuid.UUID `json:"id"`
	McLoginEnabled bool      `json:"mc_login_enabled"`
}

// mc_login_enabled 是通用布尔开关,内核不理解其业务语义(见迁移注释)。
func (q *Queries) SetMCLoginEnabled(ctx context.Context, arg SetMCLoginEnabledParams) (*IdentityAccount, error) {
	row := q.db.QueryRow(ctx, setMCLoginEnabled, arg.ID, arg.McLoginEnabled)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameLower,
		&i.Email,
		&i.Status,
		&i.McLoginEnabled,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateAccountProfile = `-- name: UpdateAccountProfile :one
UPDATE identity.account
SET username = $2, username_lower = $3, email = $4
WHERE id = $1
RETURNING id, username, username_lower, email, status, mc_login_enabled, email_verified_at, created_at, updated_at
`

type UpdateAccountProfileParams struct {
	ID            uuid.UUID `json:"id"`
	Username      string    `json:"username"`
	UsernameLower string    `json:"username_lower"`
	Email         string    `json:"email"`
}

// 只改展示层字段。username_lower 由服务层保证同步更新。
func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (*IdentityAccount, error) {
	row := q.db.QueryRow(ctx, updateAccountProfile,
		arg.ID,
		arg.Username,
		arg.UsernameLower,
		arg.Email,
	)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameLower,
		&i.Email,
		&i.Status,
		&i.McLoginEnabled,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE identity.account SET status = $2 WHERE id = $1 RETURNING id, username, username_lower, email, status, mc_login_enabled, email_verified_at, created_at, updated_at
`

type UpdateAccountStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (*IdentityAccount, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.ID, arg.Status)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameLower,
		&i.Email,
		&i.Status,
		&i.McLoginEnabled,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
