// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_list.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAccounts = `-- name: CountAccounts :one
SELECT count(*) FROM identity.account
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL
       OR username_lower LIKE $2 OR lower(email) LIKE $2)
`

type CountAccountsParams struct {
	Status pgtype.Text `json:"status"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) CountAccounts(ctx context.Context, arg CountAccountsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccounts, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, username, username_lower, email, status, mc_login_enabled, email_verified_at, created_at, updated_at FROM identity.account
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL
       OR username_lower LIKE $2 OR lower(email) LIKE $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListAccountsParams struct {
	Status pgtype.Text `json:"status"`
	Search pgtype.Text `json:"search"`
	Offset int32       `json:"offset"`
	Limit  int32       `json:"limit"`
}

// 搜索同时匹配用户名与邮箱;status 为 NULL 时不过滤状态。
func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]IdentityAccount, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.Status,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityAccount{}
	for rows.Next() {
		var i IdentityAccount
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.UsernameLower,
			&i.Email,
			&i.Status,
			&i.McLoginEnabled,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
