// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package query

import (
	"context"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT count(*) FROM identity.audit_event
WHERE ($1::uuid IS NULL OR account_id = $1::uuid)
  AND ($2::text IS NULL OR action LIKE $2::text)
  AND ($3::text IS NULL OR outcome = $3::text)
  AND ($4::timestamptz IS NULL OR occurred_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR occurred_at <= $5::timestamptz)
  AND ($6::text IS NULL OR target_type = $6::text)
  AND ($7::text IS NULL OR target_id = $7::text)
`

type CountAuditEventsParams struct {
	AccountID  pgtype.UUID        `json:"account_id"`
	Action     pgtype.Text        `json:"action"`
	Outcome    pgtype.Text        `json:"outcome"`
	From       pgtype.Timestamptz `json:"from"`
	To         pgtype.Timestamptz `json:"to"`
	TargetType pgtype.Text        `json:"target_type"`
	TargetID   pgtype.Text        `json:"target_id"`
}

func (q *Queries) CountAuditEvents(ctx context.Context, arg CountAuditEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents,
		arg.AccountID,
		arg.Action,
		arg.Outcome,
		arg.From,
		arg.To,
		arg.TargetType,
		arg.TargetID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditEventsBefore = `-- name: CountAuditEventsBefore :one
SELECT count(*) FROM identity.audit_event WHERE occurred_at < $1
`

// 归档任务用:统计某个时间点之前的行数。
func (q *Queries) CountAuditEventsBefore(ctx context.Context, occurredAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEventsBefore, occurredAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const exportAuditEvents = `-- name: ExportAuditEvents :many
SELECT id, occurred_at, account_id, actor, action, target_type, target_id,
       outcome, ip, user_agent, metadata
FROM identity.audit_event
WHERE ($1::timestamptz IS NULL OR occurred_at >= $1::timestamptz)
  AND ($2::timestamptz IS NULL OR occurred_at <= $2::timestamptz)
ORDER BY id
LIMIT $4 OFFSET $3
`

type ExportAuditEventsParams struct {
	From   pgtype.Timestamptz `json:"from"`
	To     pgtype.Timestamptz `json:"to"`
	Offset int32              `json:"offset"`
	Limit  int32              `json:"limit"`
}

// 导出 CSV 用:只按时间窗过滤,规模由调用方控制。
func (q *Queries) ExportAuditEvents(ctx context.Context, arg ExportAuditEventsParams) ([]IdentityAuditEvent, error) {
	rows, err := q.db.Query(ctx, exportAuditEvents,
		arg.From,
		arg.To,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityAuditEvent{}
	for rows.Next() {
		var i IdentityAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.AccountID,
			&i.Actor,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Outcome,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO identity.audit_event (
    account_id, actor, action, target_type, target_id, outcome, ip, user_agent, metadata)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4::text,
    $5::text,
    $6,
    $7::inet,
    $8::text,
    $9::jsonb)
RETURNING id, occurred_at, account_id, actor, action, target_type, target_id, outcome, ip, user_agent, metadata
`

type InsertAuditEventParams struct {
	AccountID  pgtype.UUID `json:"account_id"`
	Actor      string      `json:"actor"`
	Action     string      `json:"action"`
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.Text `json:"target_id"`
	Outcome    string      `json:"outcome"`
	Ip         *netip.Addr `json:"ip"`
	UserAgent  pgtype.Text `json:"user_agent"`
	Metadata   []byte      `json:"metadata"`
}

// 审计表只追加,应用层没有任何删除接口(见 docs/09-security.md 9.2)。
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (IdentityAuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.AccountID,
		arg.Actor,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Outcome,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
	)
	var i IdentityAuditEvent
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.AccountID,
		&i.Actor,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Outcome,
		&i.Ip,
		&i.UserAgent,
		&i.Metadata,
	)
	return i, err
}

const searchAuditEvents = `-- name: SearchAuditEvents :many
SELECT id, occurred_at, account_id, actor, action, target_type, target_id, outcome, ip, user_agent, metadata FROM identity.audit_event
WHERE ($1::uuid IS NULL OR account_id = $1::uuid)
  AND ($2::text IS NULL OR action LIKE $2::text)
  AND ($3::text IS NULL OR outcome = $3::text)
  AND ($4::timestamptz IS NULL OR occurred_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR occurred_at <= $5::timestamptz)
  AND ($6::text IS NULL OR target_type = $6::text)
  AND ($7::text IS NULL OR target_id = $7::text)
ORDER BY occurred_at DESC, id DESC
LIMIT $9 OFFSET $8
`

type SearchAuditEventsParams struct {
	AccountID  pgtype.UUID        `json:"account_id"`
	Action     pgtype.Text        `json:"action"`
	Outcome    pgtype.Text        `json:"outcome"`
	From       pgtype.Timestamptz `json:"from"`
	To         pgtype.Timestamptz `json:"to"`
	TargetType pgtype.Text        `json:"target_type"`
	TargetID   pgtype.Text        `json:"target_id"`
	Offset     int32              `json:"offset"`
	Limit      int32              `json:"limit"`
}

// 后台审计检索。可选参数为 NULL 时不参与过滤。
func (q *Queries) SearchAuditEvents(ctx context.Context, arg SearchAuditEventsParams) ([]IdentityAuditEvent, error) {
	rows, err := q.db.Query(ctx, searchAuditEvents,
		arg.AccountID,
		arg.Action,
		arg.Outcome,
		arg.From,
		arg.To,
		arg.TargetType,
		arg.TargetID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityAuditEvent{}
	for rows.Next() {
		var i IdentityAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.AccountID,
			&i.Actor,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Outcome,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
