// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credential.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const getCredential = `-- name: GetCredential :one
SELECT id, account_id, algo, hash, params, failed_attempts, locked_until, changed_at, must_change FROM identity.credential WHERE account_id = $1 AND algo = $2
`

type GetCredentialParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Algo      string    `json:"algo"`
}

func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (IdentityCredential, error) {
	row := q.db.QueryRow(ctx, getCredential, arg.AccountID, arg.Algo)
	var i IdentityCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Algo,
		&i.Hash,
		&i.Params,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.ChangedAt,
		&i.MustChange,
	)
	return i, err
}

const recordFailedAttempt = `-- name: RecordFailedAttempt :one
UPDATE identity.credential
SET failed_attempts = failed_attempts + 1,
    locked_until = CASE
        WHEN $1::boolean THEN now() + make_interval(secs => $2)
        ELSE locked_until
    END
WHERE account_id = $3 AND algo = $4
RETURNING id, account_id, algo, hash, params, failed_attempts, locked_until, changed_at, must_change
`

type RecordFailedAttemptParams struct {
	Lock      bool      `json:"lock"`
	LockSecs  float64   `json:"lock_secs"`
	AccountID uuid.UUID `json:"account_id"`
	Algo      string    `json:"algo"`
}

// 登录失败计数 +1。达到阈值时把 locked_until 推后 lock_secs 秒。
func (q *Queries) RecordFailedAttempt(ctx context.Context, arg RecordFailedAttemptParams) (IdentityCredential, error) {
	row := q.db.QueryRow(ctx, recordFailedAttempt,
		arg.Lock,
		arg.LockSecs,
		arg.AccountID,
		arg.Algo,
	)
	var i IdentityCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Algo,
		&i.Hash,
		&i.Params,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.ChangedAt,
		&i.MustChange,
	)
	return i, err
}

const resetFailedAttempts = `-- name: ResetFailedAttempts :one
UPDATE identity.credential
SET failed_attempts = 0, locked_until = NULL
WHERE account_id = $1 AND algo = $2
RETURNING id, account_id, algo, hash, params, failed_attempts, locked_until, changed_at, must_change
`

type ResetFailedAttemptsParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Algo      string    `json:"algo"`
}

// 登录成功后清零。
func (q *Queries) ResetFailedAttempts(ctx context.Context, arg ResetFailedAttemptsParams) (IdentityCredential, error) {
	row := q.db.QueryRow(ctx, resetFailedAttempts, arg.AccountID, arg.Algo)
	var i IdentityCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Algo,
		&i.Hash,
		&i.Params,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.ChangedAt,
		&i.MustChange,
	)
	return i, err
}

const setCredentialMustChange = `-- name: SetCredentialMustChange :exec
UPDATE identity.credential
SET must_change = $3
WHERE account_id = $1 AND algo = $2
`

type SetCredentialMustChangeParams struct {
	AccountID  uuid.UUID `json:"account_id"`
	Algo       string    `json:"algo"`
	MustChange bool      `json:"must_change"`
}

// 首登强制改密(P1)的真源开关:引导建号置 true,改密/重置密码置 false。
// 不并进 UpsertCredential 是因为「写入新的哈希」和「要求用户改密」是两件
// 独立的事:引导流程写完哈希还要再要求改密,合并会逼调用方打擦边球。
func (q *Queries) SetCredentialMustChange(ctx context.Context, arg SetCredentialMustChangeParams) error {
	_, err := q.db.Exec(ctx, setCredentialMustChange, arg.AccountID, arg.Algo, arg.MustChange)
	return err
}

const touchCredentialChangedAt = `-- name: TouchCredentialChangedAt :exec
UPDATE identity.credential SET changed_at = now() WHERE account_id = $1 AND algo = $2
`

type TouchCredentialChangedAtParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Algo      string    `json:"algo"`
}

func (q *Queries) TouchCredentialChangedAt(ctx context.Context, arg TouchCredentialChangedAtParams) error {
	_, err := q.db.Exec(ctx, touchCredentialChangedAt, arg.AccountID, arg.Algo)
	return err
}

const upsertCredential = `-- name: UpsertCredential :one
INSERT INTO identity.credential (account_id, algo, hash, params)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, algo) DO UPDATE
SET hash = EXCLUDED.hash,
    params = EXCLUDED.params,
    failed_attempts = 0,
    locked_until = NULL,
    changed_at = now()
RETURNING id, account_id, algo, hash, params, failed_attempts, locked_until, changed_at, must_change
`

type UpsertCredentialParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Algo      string    `json:"algo"`
	Hash      string    `json:"hash"`
	Params    []byte    `json:"params"`
}

// 每账号每算法一条(UNIQUE(account_id, algo)),支持多算法并存迁移。
func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) (IdentityCredential, error) {
	row := q.db.QueryRow(ctx, upsertCredential,
		arg.AccountID,
		arg.Algo,
		arg.Hash,
		arg.Params,
	)
	var i IdentityCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Algo,
		&i.Hash,
		&i.Params,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.ChangedAt,
		&i.MustChange,
	)
	return i, err
}
