// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credential.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCredential = `-- name: GetCredential :one
SELECT id, account_id, algo, hash, params, failed_attempts, locked_until, changed_at FROM identity.credential WHERE account_id = $1 AND algo = $2
`

type GetCredentialParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Algo      string    `json:"algo"`
}

func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (*IdentityCredential, error) {
	row := q.db.QueryRow(ctx, getCredential, arg.AccountID, arg.Algo)
	var i IdentityCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Algo,
		&i.Hash,
		&i.Params,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.ChangedAt,
	)
	return &i, err
}

const recordFailedAttempt = `-- name: RecordFailedAttempt :one
UPDATE identity.credential
SET failed_attempts = failed_attempts + 1,
    locked_until = CASE WHEN $3 THEN now() + make_interval(secs => $4) ELSE locked_until END
WHERE account_id = $1 AND algo = $2
RETURNING id, account_id, algo, hash, params, failed_attempts, locked_until, changed_at
`

type RecordFailedAttemptParams struct {
	AccountID   uuid.UUID          `json:"account_id"`
	Algo        string             `json:"algo"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	Secs        float64            `json:"secs"`
}

// 登录失败计数 +1。达到阈值时同时写 locked_until。
func (q *Queries) RecordFailedAttempt(ctx context.Context, arg RecordFailedAttemptParams) (*IdentityCredential, error) {
	row := q.db.QueryRow(ctx, recordFailedAttempt,
		arg.AccountID,
		arg.Algo,
		arg.LockedUntil,
		arg.Secs,
	)
	var i IdentityCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Algo,
		&i.Hash,
		&i.Params,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.ChangedAt,
	)
	return &i, err
}

const resetFailedAttempts = `-- name: ResetFailedAttempts :one
UPDATE identity.credential
SET failed_attempts = 0, locked_until = NULL
WHERE account_id = $1 AND algo = $2
RETURNING id, account_id, algo, hash, params, failed_attempts, locked_until, changed_at
`

type ResetFailedAttemptsParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Algo      string    `json:"algo"`
}

// 登录成功后清零。
func (q *Queries) ResetFailedAttempts(ctx context.Context, arg ResetFailedAttemptsParams) (*IdentityCredential, error) {
	row := q.db.QueryRow(ctx, resetFailedAttempts, arg.AccountID, arg.Algo)
	var i IdentityCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Algo,
		&i.Hash,
		&i.Params,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.ChangedAt,
	)
	return &i, err
}

const touchCredentialChangedAt = `-- name: TouchCredentialChangedAt :exec
UPDATE identity.credential SET changed_at = now() WHERE account_id = $1 AND algo = $2
`

type TouchCredentialChangedAtParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Algo      string    `json:"algo"`
}

func (q *Queries) TouchCredentialChangedAt(ctx context.Context, arg TouchCredentialChangedAtParams) error {
	_, err := q.db.Exec(ctx, touchCredentialChangedAt, arg.AccountID, arg.Algo)
	return err
}

const upsertCredential = `-- name: UpsertCredential :one
INSERT INTO identity.credential (account_id, algo, hash, params)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, algo) DO UPDATE
SET hash = EXCLUDED.hash,
    params = EXCLUDED.params,
    failed_attempts = 0,
    locked_until = NULL,
    changed_at = now()
RETURNING id, account_id, algo, hash, params, failed_attempts, locked_until, changed_at
`

type UpsertCredentialParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Algo      string    `json:"algo"`
	Hash      string    `json:"hash"`
	Params    []byte    `json:"params"`
}

// 每账号每算法一条(UNIQUE(account_id, algo)),支持多算法并存迁移。
func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) (*IdentityCredential, error) {
	row := q.db.QueryRow(ctx, upsertCredential,
		arg.AccountID,
		arg.Algo,
		arg.Hash,
		arg.Params,
	)
	var i IdentityCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Algo,
		&i.Hash,
		&i.Params,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.ChangedAt,
	)
	return &i, err
}
