// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_token.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeEmailToken = `-- name: ConsumeEmailToken :one
UPDATE identity.email_token SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING id, account_id, token_hash, purpose, expires_at, used_at, created_at
`

// 一次性使用:条件里带 used_at IS NULL,天然防重放。
func (q *Queries) ConsumeEmailToken(ctx context.Context, tokenHash []byte) (*IdentityEmailToken, error) {
	row := q.db.QueryRow(ctx, consumeEmailToken, tokenHash)
	var i IdentityEmailToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const countEmailTokensSince = `-- name: CountEmailTokensSince :one
SELECT count(*) FROM identity.email_token
WHERE account_id = $1 AND purpose = $2 AND created_at > $3
`

type CountEmailTokensSinceParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Purpose   string    `json:"purpose"`
	CreatedAt time.Time `json:"created_at"`
}

// 邮件每日发送上限(5 次/天)。
func (q *Queries) CountEmailTokensSince(ctx context.Context, arg CountEmailTokensSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmailTokensSince, arg.AccountID, arg.Purpose, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailToken = `-- name: CreateEmailToken :one
INSERT INTO identity.email_token (account_id, token_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, token_hash, purpose, expires_at, used_at, created_at
`

type CreateEmailTokenParams struct {
	AccountID uuid.UUID `json:"account_id"`
	TokenHash []byte    `json:"token_hash"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (*IdentityEmailToken, error) {
	row := q.db.QueryRow(ctx, createEmailToken,
		arg.AccountID,
		arg.TokenHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i IdentityEmailToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteExpiredEmailTokens = `-- name: DeleteExpiredEmailTokens :execrows
DELETE FROM identity.email_token WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredEmailTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEmailTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmailTokenByHash = `-- name: GetEmailTokenByHash :one
SELECT id, account_id, token_hash, purpose, expires_at, used_at, created_at FROM identity.email_token
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
`

// 只取未使用且未过期的。校验和标记使用在同一个事务里完成。
func (q *Queries) GetEmailTokenByHash(ctx context.Context, tokenHash []byte) (*IdentityEmailToken, error) {
	row := q.db.QueryRow(ctx, getEmailTokenByHash, tokenHash)
	var i IdentityEmailToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getLastEmailToken = `-- name: GetLastEmailToken :one
SELECT id, account_id, token_hash, purpose, expires_at, used_at, created_at FROM identity.email_token
WHERE account_id = $1 AND purpose = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLastEmailTokenParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Purpose   string    `json:"purpose"`
}

// 邮件重发冷却:看最近一次发信时间。
func (q *Queries) GetLastEmailToken(ctx context.Context, arg GetLastEmailTokenParams) (*IdentityEmailToken, error) {
	row := q.db.QueryRow(ctx, getLastEmailToken, arg.AccountID, arg.Purpose)
	var i IdentityEmailToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const invalidateEmailTokens = `-- name: InvalidateEmailTokens :execrows
UPDATE identity.email_token SET used_at = now()
WHERE account_id = $1 AND purpose = $2 AND used_at IS NULL
`

type InvalidateEmailTokensParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Purpose   string    `json:"purpose"`
}

// 重发验证邮件时作废同用途的旧令牌。
func (q *Queries) InvalidateEmailTokens(ctx context.Context, arg InvalidateEmailTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateEmailTokens, arg.AccountID, arg.Purpose)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
