// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitation.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeInvitation = `-- name: ConsumeInvitation :one
UPDATE identity.invitation
SET used_count = used_count + 1
WHERE code = $1
  AND revoked_at IS NULL
  AND expires_at > now()
  AND used_count < max_uses
  AND ($2::text IS NULL OR email IS NULL OR lower(email) = lower($2))
RETURNING id, code, email, max_uses, used_count, expires_at, created_by, created_at, revoked_at
`

type ConsumeInvitationParams struct {
	Code  string      `json:"code"`
	Email pgtype.Text `json:"email"`
}

// 核销邀请码。used_count 的上限判断放在条件里,避免读改写竞态。
// $2 是可选的邮箱绑定:邀请码绑定了邮箱时,只有该邮箱能使用。
func (q *Queries) ConsumeInvitation(ctx context.Context, arg ConsumeInvitationParams) (IdentityInvitation, error) {
	row := q.db.QueryRow(ctx, consumeInvitation, arg.Code, arg.Email)
	var i IdentityInvitation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO identity.invitation (code, email, max_uses, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, email, max_uses, used_count, expires_at, created_by, created_at, revoked_at
`

type CreateInvitationParams struct {
	Code      string      `json:"code"`
	Email     pgtype.Text `json:"email"`
	MaxUses   int32       `json:"max_uses"`
	ExpiresAt time.Time   `json:"expires_at"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (IdentityInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Code,
		arg.Email,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i IdentityInvitation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredInvitations = `-- name: DeleteExpiredInvitations :execrows
DELETE FROM identity.invitation WHERE expires_at < now() - interval '30 days'
`

func (q *Queries) DeleteExpiredInvitations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredInvitations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInvitationByCode = `-- name: GetInvitationByCode :one
SELECT id, code, email, max_uses, used_count, expires_at, created_by, created_at, revoked_at FROM identity.invitation
WHERE code = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetInvitationByCode(ctx context.Context, code string) (IdentityInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByCode, code)
	var i IdentityInvitation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT i.id, i.code, i.email, i.max_uses, i.used_count, i.expires_at, i.created_by, i.created_at, i.revoked_at, a.username AS created_by_username
FROM identity.invitation i
LEFT JOIN identity.account a ON a.id = i.created_by
WHERE ($1::text IS NULL OR i.code LIKE $1)
ORDER BY i.created_at DESC
LIMIT $2 OFFSET $3
`

type ListInvitationsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListInvitationsRow struct {
	ID                uuid.UUID          `json:"id"`
	Code              string             `json:"code"`
	Email             pgtype.Text        `json:"email"`
	MaxUses           int32              `json:"max_uses"`
	UsedCount         int32              `json:"used_count"`
	ExpiresAt         time.Time          `json:"expires_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	CreatedAt         time.Time          `json:"created_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	CreatedByUsername pgtype.Text        `json:"created_by_username"`
}

func (q *Queries) ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsRow{}
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Email,
			&i.MaxUses,
			&i.UsedCount,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.CreatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE identity.invitation SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeInvitation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
