// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: minecraft.sql

package query

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTextureReference = `-- name: AddTextureReference :exec
UPDATE minecraft.texture SET ref_count = ref_count + 1 WHERE hash = $1
`

func (q *Queries) AddTextureReference(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, addTextureReference, hash)
	return err
}

const createMCAccessToken = `-- name: CreateMCAccessToken :one

INSERT INTO minecraft.access_token (token_hash, profile_id, client_token, expires_at)
VALUES ($1::bytea, $2,
        $3::text, $4::timestamptz)
RETURNING id, token_hash, profile_id, client_token, expires_at, revoked_at, revoked_reason, created_at
`

type CreateMCAccessTokenParams struct {
	TokenHash   []byte      `json:"token_hash"`
	ProfileID   uuid.UUID   `json:"profile_id"`
	ClientToken pgtype.Text `json:"client_token"`
	ExpiresAt   time.Time   `json:"expires_at"`
}

// ---------------------------------------------------------------- 访问令牌
func (q *Queries) CreateMCAccessToken(ctx context.Context, arg CreateMCAccessTokenParams) (MinecraftAccessToken, error) {
	row := q.db.QueryRow(ctx, createMCAccessToken,
		arg.TokenHash,
		arg.ProfileID,
		arg.ClientToken,
		arg.ExpiresAt,
	)
	var i MinecraftAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ProfileID,
		&i.ClientToken,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const createMCServer = `-- name: CreateMCServer :one
INSERT INTO minecraft.server (server_id, name, shared_secret, enabled)
VALUES ($1, $2, $3,
        $4::boolean)
RETURNING id, server_id, name, shared_secret, enabled, created_at, updated_at
`

type CreateMCServerParams struct {
	ServerID     string `json:"server_id"`
	Name         string `json:"name"`
	SharedSecret string `json:"shared_secret"`
	Enabled      bool   `json:"enabled"`
}

func (q *Queries) CreateMCServer(ctx context.Context, arg CreateMCServerParams) (MinecraftServer, error) {
	row := q.db.QueryRow(ctx, createMCServer,
		arg.ServerID,
		arg.Name,
		arg.SharedSecret,
		arg.Enabled,
	)
	var i MinecraftServer
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.SharedSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMCSigningKey = `-- name: CreateMCSigningKey :one
INSERT INTO minecraft.signing_key (kid, algo, public_jwk, private_jwk_enc, status)
VALUES ($1, $2, $3::jsonb,
        $4::bytea, 'active')
RETURNING id, kid, algo, public_jwk, private_jwk_enc, status, created_at, retired_at
`

type CreateMCSigningKeyParams struct {
	Kid           string `json:"kid"`
	Algo          string `json:"algo"`
	PublicJwk     []byte `json:"public_jwk"`
	PrivateJwkEnc []byte `json:"private_jwk_enc"`
}

func (q *Queries) CreateMCSigningKey(ctx context.Context, arg CreateMCSigningKeyParams) (MinecraftSigningKey, error) {
	row := q.db.QueryRow(ctx, createMCSigningKey,
		arg.Kid,
		arg.Algo,
		arg.PublicJwk,
		arg.PrivateJwkEnc,
	)
	var i MinecraftSigningKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.Algo,
		&i.PublicJwk,
		&i.PrivateJwkEnc,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO minecraft.profile (account_id, uuid, current_name)
VALUES ($1, $2, $3)
RETURNING id, account_id, uuid, current_name, created_at, updated_at
`

type CreateProfileParams struct {
	AccountID   uuid.UUID `json:"account_id"`
	Uuid        uuid.UUID `json:"uuid"`
	CurrentName string    `json:"current_name"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (MinecraftProfile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.AccountID, arg.Uuid, arg.CurrentName)
	var i MinecraftProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Uuid,
		&i.CurrentName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServerSession = `-- name: CreateServerSession :one

INSERT INTO minecraft.server_session (profile_id, server_id, ip)
VALUES ($1, $2, $3::inet)
RETURNING id, profile_id, server_id, ip, joined_at, verified_at, disconnected_at
`

type CreateServerSessionParams struct {
	ProfileID uuid.UUID   `json:"profile_id"`
	ServerID  string      `json:"server_id"`
	Ip        *netip.Addr `json:"ip"`
}

// ---------------------------------------------------------------- 进服会话
func (q *Queries) CreateServerSession(ctx context.Context, arg CreateServerSessionParams) (MinecraftServerSession, error) {
	row := q.db.QueryRow(ctx, createServerSession, arg.ProfileID, arg.ServerID, arg.Ip)
	var i MinecraftServerSession
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ServerID,
		&i.Ip,
		&i.JoinedAt,
		&i.VerifiedAt,
		&i.DisconnectedAt,
	)
	return i, err
}

const createTexture = `-- name: CreateTexture :one
INSERT INTO minecraft.texture (hash, type, size, mime, width, height)
VALUES ($1, $2::text, $3::int,
        $4::text, $5::int, $6::int)
RETURNING id, hash, type, size, width, height, mime, ref_count, created_at, updated_at, last_used_at
`

type CreateTextureParams struct {
	Hash   string `json:"hash"`
	Type   string `json:"type"`
	Size   int32  `json:"size"`
	Mime   string `json:"mime"`
	Width  int32  `json:"width"`
	Height int32  `json:"height"`
}

func (q *Queries) CreateTexture(ctx context.Context, arg CreateTextureParams) (MinecraftTexture, error) {
	row := q.db.QueryRow(ctx, createTexture,
		arg.Hash,
		arg.Type,
		arg.Size,
		arg.Mime,
		arg.Width,
		arg.Height,
	)
	var i MinecraftTexture
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Type,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Mime,
		&i.RefCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteAvatar = `-- name: DeleteAvatar :execrows
DELETE FROM minecraft.avatar WHERE profile_id = $1
`

func (q *Queries) DeleteAvatar(ctx context.Context, profileID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAvatar, profileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredMCAccessTokens = `-- name: DeleteExpiredMCAccessTokens :execrows
DELETE FROM minecraft.access_token
WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredMCAccessTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredMCAccessTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredServerSessions = `-- name: DeleteExpiredServerSessions :execrows
DELETE FROM minecraft.server_session
WHERE joined_at < now() - $1::interval
`

func (q *Queries) DeleteExpiredServerSessions(ctx context.Context, window pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredServerSessions, window)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMCServer = `-- name: DeleteMCServer :execrows
DELETE FROM minecraft.server WHERE server_id = $1
`

func (q *Queries) DeleteMCServer(ctx context.Context, serverID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMCServer, serverID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProfileTexture = `-- name: DeleteProfileTexture :execrows
DELETE FROM minecraft.profile_texture
WHERE profile_id = $1 AND type = $2::text
`

type DeleteProfileTextureParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Type      string    `json:"type"`
}

func (q *Queries) DeleteProfileTexture(ctx context.Context, arg DeleteProfileTextureParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProfileTexture, arg.ProfileID, arg.Type)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTexture = `-- name: DeleteTexture :execrows
DELETE FROM minecraft.texture WHERE hash = $1
`

func (q *Queries) DeleteTexture(ctx context.Context, hash string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTexture, hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dropTextureReference = `-- name: DropTextureReference :execrows
UPDATE minecraft.texture SET ref_count = greatest(ref_count - 1, 0) WHERE hash = $1
`

func (q *Queries) DropTextureReference(ctx context.Context, hash string) (int64, error) {
	result, err := q.db.Exec(ctx, dropTextureReference, hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendNameRetention = `-- name: ExtendNameRetention :exec
UPDATE minecraft.name_history
SET reusable_at = $1::timestamptz
WHERE profile_id = $2
  AND (reusable_at IS NULL OR reusable_at < $1::timestamptz)
`

type ExtendNameRetentionParams struct {
	ReusableAt time.Time `json:"reusable_at"`
	ProfileID  uuid.UUID `json:"profile_id"`
}

// 把仍然有效期的旧名延长到新的保留期。改名链上可能有多个旧名,
// 逐个延长才能保证「上一次改名腾出的名字」也受同一条规则约束。
func (q *Queries) ExtendNameRetention(ctx context.Context, arg ExtendNameRetentionParams) error {
	_, err := q.db.Exec(ctx, extendNameRetention, arg.ReusableAt, arg.ProfileID)
	return err
}

const getActiveMCSigningKey = `-- name: GetActiveMCSigningKey :one

SELECT id, kid, algo, public_jwk, private_jwk_enc, status, created_at, retired_at FROM minecraft.signing_key WHERE status = 'active'
`

// ---------------------------------------------------------------- 签名密钥
func (q *Queries) GetActiveMCSigningKey(ctx context.Context) (MinecraftSigningKey, error) {
	row := q.db.QueryRow(ctx, getActiveMCSigningKey)
	var i MinecraftSigningKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.Algo,
		&i.PublicJwk,
		&i.PrivateJwkEnc,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getAvatar = `-- name: GetAvatar :one

SELECT profile_id, hash, rendered_at FROM minecraft.avatar WHERE profile_id = $1
`

// ---------------------------------------------------------------- 头像缓存
func (q *Queries) GetAvatar(ctx context.Context, profileID uuid.UUID) (MinecraftAvatar, error) {
	row := q.db.QueryRow(ctx, getAvatar, profileID)
	var i MinecraftAvatar
	err := row.Scan(&i.ProfileID, &i.Hash, &i.RenderedAt)
	return i, err
}

const getExternalBinding = `-- name: GetExternalBinding :one
SELECT id, profile_id, provider, external_user_id, base_url, enabled, created_at, updated_at FROM minecraft.external_binding WHERE profile_id = $1
`

func (q *Queries) GetExternalBinding(ctx context.Context, profileID uuid.UUID) (MinecraftExternalBinding, error) {
	row := q.db.QueryRow(ctx, getExternalBinding, profileID)
	var i MinecraftExternalBinding
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Provider,
		&i.ExternalUserID,
		&i.BaseUrl,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMCAccessToken = `-- name: GetMCAccessToken :one
SELECT id, token_hash, profile_id, client_token, expires_at, revoked_at, revoked_reason, created_at FROM minecraft.access_token WHERE token_hash = $1::bytea
`

func (q *Queries) GetMCAccessToken(ctx context.Context, tokenHash []byte) (MinecraftAccessToken, error) {
	row := q.db.QueryRow(ctx, getMCAccessToken, tokenHash)
	var i MinecraftAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ProfileID,
		&i.ClientToken,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getMCAccessTokenWithProfile = `-- name: GetMCAccessTokenWithProfile :one
SELECT t.id, t.profile_id, t.client_token, t.expires_at, t.revoked_at, t.revoked_reason,
       t.created_at,
       p.uuid, p.current_name, p.account_id
FROM minecraft.access_token t
JOIN minecraft.profile p ON p.id = t.profile_id
WHERE t.token_hash = $1::bytea
`

type GetMCAccessTokenWithProfileRow struct {
	ID            uuid.UUID          `json:"id"`
	ProfileID     uuid.UUID          `json:"profile_id"`
	ClientToken   pgtype.Text        `json:"client_token"`
	ExpiresAt     time.Time          `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
	CreatedAt     time.Time          `json:"created_at"`
	Uuid          uuid.UUID          `json:"uuid"`
	CurrentName   string             `json:"current_name"`
	AccountID     uuid.UUID          `json:"account_id"`
}

// 带 profile 联查:MC 端点的每一次令牌校验都要这个组合,
// 分两次查等于给并发刷新留了个竞态窗口。
func (q *Queries) GetMCAccessTokenWithProfile(ctx context.Context, tokenHash []byte) (GetMCAccessTokenWithProfileRow, error) {
	row := q.db.QueryRow(ctx, getMCAccessTokenWithProfile, tokenHash)
	var i GetMCAccessTokenWithProfileRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ClientToken,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.Uuid,
		&i.CurrentName,
		&i.AccountID,
	)
	return i, err
}

const getMCLoginEnabled = `-- name: GetMCLoginEnabled :one
SELECT mc_login_enabled FROM identity.account WHERE id = $1
`

func (q *Queries) GetMCLoginEnabled(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getMCLoginEnabled, id)
	var mc_login_enabled bool
	err := row.Scan(&mc_login_enabled)
	return mc_login_enabled, err
}

const getMCServer = `-- name: GetMCServer :one

SELECT id, server_id, name, shared_secret, enabled, created_at, updated_at FROM minecraft.server WHERE server_id = $1
`

// ---------------------------------------------------------------- MC 服务器
func (q *Queries) GetMCServer(ctx context.Context, serverID string) (MinecraftServer, error) {
	row := q.db.QueryRow(ctx, getMCServer, serverID)
	var i MinecraftServer
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.SharedSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMCSigningKey = `-- name: GetMCSigningKey :one
SELECT id, kid, algo, public_jwk, private_jwk_enc, status, created_at, retired_at FROM minecraft.signing_key WHERE kid = $1
`

func (q *Queries) GetMCSigningKey(ctx context.Context, kid string) (MinecraftSigningKey, error) {
	row := q.db.QueryRow(ctx, getMCSigningKey, kid)
	var i MinecraftSigningKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.Algo,
		&i.PublicJwk,
		&i.PrivateJwkEnc,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getNameHistory = `-- name: GetNameHistory :many
SELECT id, profile_id, name, changed_at, reusable_at FROM minecraft.name_history
WHERE profile_id = $1
ORDER BY changed_at DESC
`

func (q *Queries) GetNameHistory(ctx context.Context, profileID uuid.UUID) ([]MinecraftNameHistory, error) {
	rows, err := q.db.Query(ctx, getNameHistory, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinecraftNameHistory{}
	for rows.Next() {
		var i MinecraftNameHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.ChangedAt,
			&i.ReusableAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileByAccount = `-- name: GetProfileByAccount :one
SELECT id, account_id, uuid, current_name, created_at, updated_at FROM minecraft.profile WHERE account_id = $1
`

func (q *Queries) GetProfileByAccount(ctx context.Context, accountID uuid.UUID) (MinecraftProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByAccount, accountID)
	var i MinecraftProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Uuid,
		&i.CurrentName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByName = `-- name: GetProfileByName :one
SELECT id, account_id, uuid, current_name, created_at, updated_at FROM minecraft.profile WHERE current_name = $1
`

func (q *Queries) GetProfileByName(ctx context.Context, currentName string) (MinecraftProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByName, currentName)
	var i MinecraftProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Uuid,
		&i.CurrentName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUUID = `-- name: GetProfileByUUID :one
SELECT id, account_id, uuid, current_name, created_at, updated_at FROM minecraft.profile WHERE uuid = $1
`

func (q *Queries) GetProfileByUUID(ctx context.Context, argUuid uuid.UUID) (MinecraftProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByUUID, argUuid)
	var i MinecraftProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Uuid,
		&i.CurrentName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileTexture = `-- name: GetProfileTexture :one

SELECT t.id, t.hash, t.type, t.size, t.width, t.height, t.mime, t.ref_count, t.created_at, t.updated_at, t.last_used_at, pt.type AS bound_type, pt.profile_id AS bound_profile
FROM minecraft.profile_texture pt
JOIN minecraft.texture t ON t.id = pt.texture_id
WHERE pt.profile_id = $1 AND pt.type = $2::text
`

type GetProfileTextureParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Type      string    `json:"type"`
}

type GetProfileTextureRow struct {
	ID           uuid.UUID `json:"id"`
	Hash         string    `json:"hash"`
	Type         string    `json:"type"`
	Size         int32     `json:"size"`
	Width        int32     `json:"width"`
	Height       int32     `json:"height"`
	Mime         string    `json:"mime"`
	RefCount     int32     `json:"ref_count"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	LastUsedAt   time.Time `json:"last_used_at"`
	BoundType    string    `json:"bound_type"`
	BoundProfile uuid.UUID `json:"bound_profile"`
}

// ---------------------------------------------------------------- 材质绑定
func (q *Queries) GetProfileTexture(ctx context.Context, arg GetProfileTextureParams) (GetProfileTextureRow, error) {
	row := q.db.QueryRow(ctx, getProfileTexture, arg.ProfileID, arg.Type)
	var i GetProfileTextureRow
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Type,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Mime,
		&i.RefCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.BoundType,
		&i.BoundProfile,
	)
	return i, err
}

const getReusableNameConflict = `-- name: GetReusableNameConflict :one
SELECT id, profile_id, name, changed_at, reusable_at FROM minecraft.name_history
WHERE lower(name) = lower($1)
  AND (reusable_at IS NULL OR reusable_at > now())
ORDER BY changed_at DESC
LIMIT 1
`

// 查这个名字是否还在保留期内。reusable_at IS NULL 表示永久保留。
func (q *Queries) GetReusableNameConflict(ctx context.Context, name string) (MinecraftNameHistory, error) {
	row := q.db.QueryRow(ctx, getReusableNameConflict, name)
	var i MinecraftNameHistory
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.ChangedAt,
		&i.ReusableAt,
	)
	return i, err
}

const getServerSession = `-- name: GetServerSession :one
SELECT id, profile_id, server_id, ip, joined_at, verified_at, disconnected_at FROM minecraft.server_session WHERE server_id = $1
`

func (q *Queries) GetServerSession(ctx context.Context, serverID string) (MinecraftServerSession, error) {
	row := q.db.QueryRow(ctx, getServerSession, serverID)
	var i MinecraftServerSession
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ServerID,
		&i.Ip,
		&i.JoinedAt,
		&i.VerifiedAt,
		&i.DisconnectedAt,
	)
	return i, err
}

const getTextureByHash = `-- name: GetTextureByHash :one

SELECT id, hash, type, size, width, height, mime, ref_count, created_at, updated_at, last_used_at FROM minecraft.texture WHERE hash = $1
`

// ---------------------------------------------------------------- 纹理
func (q *Queries) GetTextureByHash(ctx context.Context, hash string) (MinecraftTexture, error) {
	row := q.db.QueryRow(ctx, getTextureByHash, hash)
	var i MinecraftTexture
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Type,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Mime,
		&i.RefCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertNameHistory = `-- name: InsertNameHistory :one

INSERT INTO minecraft.name_history (profile_id, name, reusable_at)
VALUES ($1, $2, $3::timestamptz)
RETURNING id, profile_id, name, changed_at, reusable_at
`

type InsertNameHistoryParams struct {
	ProfileID  uuid.UUID          `json:"profile_id"`
	Name       string             `json:"name"`
	ReusableAt pgtype.Timestamptz `json:"reusable_at"`
}

// ---------------------------------------------------------------- 改名历史
func (q *Queries) InsertNameHistory(ctx context.Context, arg InsertNameHistoryParams) (MinecraftNameHistory, error) {
	row := q.db.QueryRow(ctx, insertNameHistory, arg.ProfileID, arg.Name, arg.ReusableAt)
	var i MinecraftNameHistory
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.ChangedAt,
		&i.ReusableAt,
	)
	return i, err
}

const listGarbageTextures = `-- name: ListGarbageTextures :many
SELECT id, hash, type, size, width, height, mime, ref_count, created_at, updated_at, last_used_at FROM minecraft.texture
WHERE ref_count = 0 AND last_accessed_at < now() - $1::interval
LIMIT $2::int
`

type ListGarbageTexturesParams struct {
	Grace pgtype.Interval `json:"grace"`
	Batch int32           `json:"batch"`
}

// 回收候选:引用计数归零且超过保留期的纹理。
func (q *Queries) ListGarbageTextures(ctx context.Context, arg ListGarbageTexturesParams) ([]MinecraftTexture, error) {
	rows, err := q.db.Query(ctx, listGarbageTextures, arg.Grace, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinecraftTexture{}
	for rows.Next() {
		var i MinecraftTexture
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.Type,
			&i.Size,
			&i.Width,
			&i.Height,
			&i.Mime,
			&i.RefCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCServers = `-- name: ListMCServers :many
SELECT id, server_id, name, shared_secret, enabled, created_at, updated_at FROM minecraft.server ORDER BY created_at
`

func (q *Queries) ListMCServers(ctx context.Context) ([]MinecraftServer, error) {
	rows, err := q.db.Query(ctx, listMCServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinecraftServer{}
	for rows.Next() {
		var i MinecraftServer
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.SharedSecret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCSigningKeys = `-- name: ListMCSigningKeys :many
SELECT id, kid, algo, public_jwk, private_jwk_enc, status, created_at, retired_at FROM minecraft.signing_key ORDER BY created_at DESC
`

func (q *Queries) ListMCSigningKeys(ctx context.Context) ([]MinecraftSigningKey, error) {
	rows, err := q.db.Query(ctx, listMCSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinecraftSigningKey{}
	for rows.Next() {
		var i MinecraftSigningKey
		if err := rows.Scan(
			&i.ID,
			&i.Kid,
			&i.Algo,
			&i.PublicJwk,
			&i.PrivateJwkEnc,
			&i.Status,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingServerSessions = `-- name: ListPendingServerSessions :many
SELECT id, profile_id, server_id, ip, joined_at, verified_at, disconnected_at FROM minecraft.server_session
WHERE profile_id = $1
  AND verified_at IS NULL
  AND joined_at > now() - $2::interval
ORDER BY joined_at DESC
LIMIT 20
`

type ListPendingServerSessionsParams struct {
	ProfileID uuid.UUID       `json:"profile_id"`
	Window    pgtype.Interval `json:"window"`
}

// 列出某玩家尚未核销、且仍在时间窗内的进服会话。
//
// hasJoined 收到的是**签名**(serverIdHash),不是原始 serverId,
// 要重算就得把该玩家的候选会话逐个试一遍。因此候选集必须小 ——
// 时间窗和「一次核销」两条约束共同把它压到个位数。
func (q *Queries) ListPendingServerSessions(ctx context.Context, arg ListPendingServerSessionsParams) ([]MinecraftServerSession, error) {
	rows, err := q.db.Query(ctx, listPendingServerSessions, arg.ProfileID, arg.Window)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinecraftServerSession{}
	for rows.Next() {
		var i MinecraftServerSession
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ServerID,
			&i.Ip,
			&i.JoinedAt,
			&i.VerifiedAt,
			&i.DisconnectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingServerSessionsBefore = `-- name: ListPendingServerSessionsBefore :many
SELECT id, profile_id, server_id, ip, joined_at, verified_at, disconnected_at FROM minecraft.server_session
WHERE profile_id = $1
  AND verified_at IS NULL
  AND joined_at >= $2::timestamptz
ORDER BY joined_at DESC
LIMIT 20
`

type ListPendingServerSessionsBeforeParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Cutoff    time.Time `json:"cutoff"`
}

// 同上,但用**调用方算好的截止时间**而不是数据库的 now()。
//
// 时间窗的判定必须用应用时钟:服务注入的是可替换的 Clock,
// 测试要靠推进它来验证过期行为;而数据库的 now() 推不动。
// 顺带消除了「数据库时钟与进程时钟漂移」带来的判定不一致。
func (q *Queries) ListPendingServerSessionsBefore(ctx context.Context, arg ListPendingServerSessionsBeforeParams) ([]MinecraftServerSession, error) {
	rows, err := q.db.Query(ctx, listPendingServerSessionsBefore, arg.ProfileID, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinecraftServerSession{}
	for rows.Next() {
		var i MinecraftServerSession
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ServerID,
			&i.Ip,
			&i.JoinedAt,
			&i.VerifiedAt,
			&i.DisconnectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileTextures = `-- name: ListProfileTextures :many
SELECT profile_id, texture_id, type, updated_at FROM minecraft.profile_texture WHERE profile_id = $1
`

func (q *Queries) ListProfileTextures(ctx context.Context, profileID uuid.UUID) ([]MinecraftProfileTexture, error) {
	rows, err := q.db.Query(ctx, listProfileTextures, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinecraftProfileTexture{}
	for rows.Next() {
		var i MinecraftProfileTexture
		if err := rows.Scan(
			&i.ProfileID,
			&i.TextureID,
			&i.Type,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilesByAccount = `-- name: ListProfilesByAccount :many
SELECT id, account_id, uuid, current_name, created_at, updated_at FROM minecraft.profile WHERE account_id = $1
`

func (q *Queries) ListProfilesByAccount(ctx context.Context, accountID uuid.UUID) ([]MinecraftProfile, error) {
	rows, err := q.db.Query(ctx, listProfilesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinecraftProfile{}
	for rows.Next() {
		var i MinecraftProfile
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Uuid,
			&i.CurrentName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markServerSessionVerified = `-- name: MarkServerSessionVerified :execrows
UPDATE minecraft.server_session SET verified_at = now()
WHERE server_id = $1 AND verified_at IS NULL
`

// 防重放:同一 serverId 只允许成功核销一次。
// 条件里带 verified_at IS NULL,第二次 hasJoined 命中 0 行。
func (q *Queries) MarkServerSessionVerified(ctx context.Context, serverID string) (int64, error) {
	result, err := q.db.Exec(ctx, markServerSessionVerified, serverID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameProfile = `-- name: RenameProfile :one
UPDATE minecraft.profile
SET current_name = $1, updated_at = now()
WHERE id = $2
RETURNING id, account_id, uuid, current_name, created_at, updated_at
`

type RenameProfileParams struct {
	CurrentName string    `json:"current_name"`
	ID          uuid.UUID `json:"id"`
}

// 改名。current_name 上的唯一索引会挡住重名 —— 这是最后一道防线,
// 上层的前置检查只是为了给出可读的错误信息。
func (q *Queries) RenameProfile(ctx context.Context, arg RenameProfileParams) (MinecraftProfile, error) {
	row := q.db.QueryRow(ctx, renameProfile, arg.CurrentName, arg.ID)
	var i MinecraftProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Uuid,
		&i.CurrentName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retireActiveMCSigningKey = `-- name: RetireActiveMCSigningKey :exec
UPDATE minecraft.signing_key
SET status = 'retired', retired_at = now()
WHERE status = 'active'
`

// 与 oidc 侧同样的理由:同一语句里改 CTE 再往带唯一索引的列插值,
// PostgreSQL 看不见 CTE 的效果,必然撞 duplicate key。拆成两条。
func (q *Queries) RetireActiveMCSigningKey(ctx context.Context) error {
	_, err := q.db.Exec(ctx, retireActiveMCSigningKey)
	return err
}

const revokeMCAccessToken = `-- name: RevokeMCAccessToken :execrows
UPDATE minecraft.access_token
SET revoked_at = now(), revoked_reason = $1::text
WHERE token_hash = $2::bytea AND revoked_at IS NULL
`

type RevokeMCAccessTokenParams struct {
	Reason    string `json:"reason"`
	TokenHash []byte `json:"token_hash"`
}

func (q *Queries) RevokeMCAccessToken(ctx context.Context, arg RevokeMCAccessTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMCAccessToken, arg.Reason, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeMCAccessTokensByProfile = `-- name: RevokeMCAccessTokensByProfile :execrows
UPDATE minecraft.access_token
SET revoked_at = now(), revoked_reason = $1::text
WHERE profile_id = $2 AND revoked_at IS NULL
`

type RevokeMCAccessTokensByProfileParams struct {
	Reason    string    `json:"reason"`
	ProfileID uuid.UUID `json:"profile_id"`
}

func (q *Queries) RevokeMCAccessTokensByProfile(ctx context.Context, arg RevokeMCAccessTokensByProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMCAccessTokensByProfile, arg.Reason, arg.ProfileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateMCAccessToken = `-- name: RotateMCAccessToken :one
WITH old AS (
    UPDATE minecraft.access_token
    SET revoked_at = now(), revoked_reason = 'refreshed'
    WHERE token_hash = $3::bytea AND revoked_at IS NULL
    RETURNING profile_id, client_token
)
INSERT INTO minecraft.access_token (token_hash, profile_id, client_token, expires_at)
SELECT $1::bytea, old.profile_id, old.client_token,
       $2::timestamptz
FROM old
RETURNING id, token_hash, profile_id, client_token, expires_at, revoked_at, revoked_reason, created_at
`

type RotateMCAccessTokenParams struct {
	NewHash   []byte    `json:"new_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	OldHash   []byte    `json:"old_hash"`
}

// 刷新:吊销旧令牌并签发新的一条,在同一条语句里完成。
//
// 分成两步的话,中间崩溃会留下「旧令牌已废、新令牌没发」的空窗,
// 玩家会被直接踢下线。
func (q *Queries) RotateMCAccessToken(ctx context.Context, arg RotateMCAccessTokenParams) (MinecraftAccessToken, error) {
	row := q.db.QueryRow(ctx, rotateMCAccessToken, arg.NewHash, arg.ExpiresAt, arg.OldHash)
	var i MinecraftAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ProfileID,
		&i.ClientToken,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const touchTexture = `-- name: TouchTexture :exec
UPDATE minecraft.texture SET last_accessed_at = now() WHERE hash = $1
`

func (q *Queries) TouchTexture(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, touchTexture, hash)
	return err
}

const updateMCServer = `-- name: UpdateMCServer :one
UPDATE minecraft.server
SET name = $1, shared_secret = $2,
    enabled = $3::boolean, updated_at = now()
WHERE server_id = $4
RETURNING id, server_id, name, shared_secret, enabled, created_at, updated_at
`

type UpdateMCServerParams struct {
	Name         string `json:"name"`
	SharedSecret string `json:"shared_secret"`
	Enabled      bool   `json:"enabled"`
	ServerID     string `json:"server_id"`
}

func (q *Queries) UpdateMCServer(ctx context.Context, arg UpdateMCServerParams) (MinecraftServer, error) {
	row := q.db.QueryRow(ctx, updateMCServer,
		arg.Name,
		arg.SharedSecret,
		arg.Enabled,
		arg.ServerID,
	)
	var i MinecraftServer
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.SharedSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAvatar = `-- name: UpsertAvatar :exec
INSERT INTO minecraft.avatar (profile_id, hash)
VALUES ($1, $2::text)
ON CONFLICT (profile_id) DO UPDATE
SET hash = EXCLUDED.hash, rendered_at = now()
`

type UpsertAvatarParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Hash      string    `json:"hash"`
}

// 表里**不存图像**,只存「这张头像是从哪份皮肤渲染出来的」。
//
// 图像本身在 storage 的 avatars/<profile_uuid>.png。这样分是因为
// 图像是二进制大对象,进数据库会让一次 SELECT 拖上几 MB;
// 而这里需要的只是「缓存是否失效」这一个判断。
func (q *Queries) UpsertAvatar(ctx context.Context, arg UpsertAvatarParams) error {
	_, err := q.db.Exec(ctx, upsertAvatar, arg.ProfileID, arg.Hash)
	return err
}

const upsertExternalBinding = `-- name: UpsertExternalBinding :exec
INSERT INTO minecraft.external_binding (profile_id, provider, external_user_id, base_url, enabled)
VALUES ($1, $2::text, $3::text,
        $4::text, $5::boolean)
ON CONFLICT (profile_id) DO UPDATE
SET provider = EXCLUDED.provider, external_user_id = EXCLUDED.external_user_id,
    base_url = EXCLUDED.base_url, enabled = EXCLUDED.enabled, updated_at = now()
`

type UpsertExternalBindingParams struct {
	ProfileID      uuid.UUID `json:"profile_id"`
	Provider       string    `json:"provider"`
	ExternalUserID string    `json:"external_user_id"`
	BaseUrl        string    `json:"base_url"`
	Enabled        bool      `json:"enabled"`
}

// 一个 profile 只绑定一个外部站(profile_id 上有唯一约束),
// 所以按 profile_id 冲突消解,而不是按 (profile_id, kind)。
//
// base_url 存进数据而不是只读配置:玩家指向自建镜像时不需要重启服务。
func (q *Queries) UpsertExternalBinding(ctx context.Context, arg UpsertExternalBindingParams) error {
	_, err := q.db.Exec(ctx, upsertExternalBinding,
		arg.ProfileID,
		arg.Provider,
		arg.ExternalUserID,
		arg.BaseUrl,
		arg.Enabled,
	)
	return err
}

const upsertProfileTexture = `-- name: UpsertProfileTexture :exec
INSERT INTO minecraft.profile_texture (profile_id, texture_id, type)
VALUES ($1, $2, $3::text)
ON CONFLICT (profile_id, type) DO UPDATE
SET texture_id = EXCLUDED.texture_id, updated_at = now()
RETURNING texture_id
`

type UpsertProfileTextureParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	TextureID uuid.UUID `json:"texture_id"`
	Type      string    `json:"type"`
}

func (q *Queries) UpsertProfileTexture(ctx context.Context, arg UpsertProfileTextureParams) error {
	_, err := q.db.Exec(ctx, upsertProfileTexture, arg.ProfileID, arg.TextureID, arg.Type)
	return err
}
