// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: minecraft.sql

package query

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMCAccessToken = `-- name: CreateMCAccessToken :one

INSERT INTO minecraft.access_token (token_hash, profile_id, client_token, expires_at)
VALUES ($1::bytea, $2,
        $3::text, $4::timestamptz)
RETURNING id, token_hash, profile_id, client_token, expires_at, revoked_at, revoked_reason, created_at
`

type CreateMCAccessTokenParams struct {
	TokenHash   []byte      `json:"token_hash"`
	ProfileID   uuid.UUID   `json:"profile_id"`
	ClientToken pgtype.Text `json:"client_token"`
	ExpiresAt   time.Time   `json:"expires_at"`
}

// ---------------------------------------------------------------- 访问令牌
func (q *Queries) CreateMCAccessToken(ctx context.Context, arg CreateMCAccessTokenParams) (MinecraftAccessToken, error) {
	row := q.db.QueryRow(ctx, createMCAccessToken,
		arg.TokenHash,
		arg.ProfileID,
		arg.ClientToken,
		arg.ExpiresAt,
	)
	var i MinecraftAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ProfileID,
		&i.ClientToken,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const createMCServer = `-- name: CreateMCServer :one
INSERT INTO minecraft.server (server_id, name, shared_secret, enabled)
VALUES ($1, $2, $3,
        $4::boolean)
RETURNING id, server_id, name, shared_secret, enabled, created_at, updated_at
`

type CreateMCServerParams struct {
	ServerID     string `json:"server_id"`
	Name         string `json:"name"`
	SharedSecret string `json:"shared_secret"`
	Enabled      bool   `json:"enabled"`
}

func (q *Queries) CreateMCServer(ctx context.Context, arg CreateMCServerParams) (MinecraftServer, error) {
	row := q.db.QueryRow(ctx, createMCServer,
		arg.ServerID,
		arg.Name,
		arg.SharedSecret,
		arg.Enabled,
	)
	var i MinecraftServer
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.SharedSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMCSigningKey = `-- name: CreateMCSigningKey :one
INSERT INTO minecraft.signing_key (kid, algo, public_jwk, private_jwk_enc, status)
VALUES ($1, $2, $3::jsonb,
        $4::bytea, 'active')
RETURNING id, kid, algo, public_jwk, private_jwk_enc, status, created_at, retired_at
`

type CreateMCSigningKeyParams struct {
	Kid           string `json:"kid"`
	Algo          string `json:"algo"`
	PublicJwk     []byte `json:"public_jwk"`
	PrivateJwkEnc []byte `json:"private_jwk_enc"`
}

func (q *Queries) CreateMCSigningKey(ctx context.Context, arg CreateMCSigningKeyParams) (MinecraftSigningKey, error) {
	row := q.db.QueryRow(ctx, createMCSigningKey,
		arg.Kid,
		arg.Algo,
		arg.PublicJwk,
		arg.PrivateJwkEnc,
	)
	var i MinecraftSigningKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.Algo,
		&i.PublicJwk,
		&i.PrivateJwkEnc,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO minecraft.profile (account_id, uuid, current_name)
VALUES ($1, $2, $3)
RETURNING id, account_id, uuid, current_name, created_at, updated_at
`

type CreateProfileParams struct {
	AccountID   uuid.UUID `json:"account_id"`
	Uuid        uuid.UUID `json:"uuid"`
	CurrentName string    `json:"current_name"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (MinecraftProfile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.AccountID, arg.Uuid, arg.CurrentName)
	var i MinecraftProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Uuid,
		&i.CurrentName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServerSession = `-- name: CreateServerSession :one

INSERT INTO minecraft.server_session (profile_id, server_id, ip)
VALUES ($1, $2, $3::inet)
RETURNING id, profile_id, server_id, ip, joined_at, verified_at, disconnected_at
`

type CreateServerSessionParams struct {
	ProfileID uuid.UUID   `json:"profile_id"`
	ServerID  string      `json:"server_id"`
	Ip        *netip.Addr `json:"ip"`
}

// ---------------------------------------------------------------- 进服会话
func (q *Queries) CreateServerSession(ctx context.Context, arg CreateServerSessionParams) (MinecraftServerSession, error) {
	row := q.db.QueryRow(ctx, createServerSession, arg.ProfileID, arg.ServerID, arg.Ip)
	var i MinecraftServerSession
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ServerID,
		&i.Ip,
		&i.JoinedAt,
		&i.VerifiedAt,
		&i.DisconnectedAt,
	)
	return i, err
}

const deleteExpiredMCAccessTokens = `-- name: DeleteExpiredMCAccessTokens :execrows
DELETE FROM minecraft.access_token
WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredMCAccessTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredMCAccessTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredServerSessions = `-- name: DeleteExpiredServerSessions :execrows
DELETE FROM minecraft.server_session
WHERE joined_at < now() - $1::interval
`

func (q *Queries) DeleteExpiredServerSessions(ctx context.Context, window pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredServerSessions, window)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMCServer = `-- name: DeleteMCServer :execrows
DELETE FROM minecraft.server WHERE server_id = $1
`

func (q *Queries) DeleteMCServer(ctx context.Context, serverID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMCServer, serverID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendNameRetention = `-- name: ExtendNameRetention :exec
UPDATE minecraft.name_history
SET reusable_at = $1::timestamptz
WHERE profile_id = $2
  AND (reusable_at IS NULL OR reusable_at < $1::timestamptz)
`

type ExtendNameRetentionParams struct {
	ReusableAt time.Time `json:"reusable_at"`
	ProfileID  uuid.UUID `json:"profile_id"`
}

// 把仍然有效期的旧名延长到新的保留期。改名链上可能有多个旧名,
// 逐个延长才能保证「上一次改名腾出的名字」也受同一条规则约束。
func (q *Queries) ExtendNameRetention(ctx context.Context, arg ExtendNameRetentionParams) error {
	_, err := q.db.Exec(ctx, extendNameRetention, arg.ReusableAt, arg.ProfileID)
	return err
}

const getActiveMCSigningKey = `-- name: GetActiveMCSigningKey :one

SELECT id, kid, algo, public_jwk, private_jwk_enc, status, created_at, retired_at FROM minecraft.signing_key WHERE status = 'active'
`

// ---------------------------------------------------------------- 签名密钥
func (q *Queries) GetActiveMCSigningKey(ctx context.Context) (MinecraftSigningKey, error) {
	row := q.db.QueryRow(ctx, getActiveMCSigningKey)
	var i MinecraftSigningKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.Algo,
		&i.PublicJwk,
		&i.PrivateJwkEnc,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getMCAccessToken = `-- name: GetMCAccessToken :one
SELECT id, token_hash, profile_id, client_token, expires_at, revoked_at, revoked_reason, created_at FROM minecraft.access_token WHERE token_hash = $1::bytea
`

func (q *Queries) GetMCAccessToken(ctx context.Context, tokenHash []byte) (MinecraftAccessToken, error) {
	row := q.db.QueryRow(ctx, getMCAccessToken, tokenHash)
	var i MinecraftAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ProfileID,
		&i.ClientToken,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getMCAccessTokenWithProfile = `-- name: GetMCAccessTokenWithProfile :one
SELECT t.id, t.profile_id, t.client_token, t.expires_at, t.revoked_at, t.revoked_reason,
       t.created_at,
       p.uuid, p.current_name, p.account_id
FROM minecraft.access_token t
JOIN minecraft.profile p ON p.id = t.profile_id
WHERE t.token_hash = $1::bytea
`

type GetMCAccessTokenWithProfileRow struct {
	ID            uuid.UUID          `json:"id"`
	ProfileID     uuid.UUID          `json:"profile_id"`
	ClientToken   pgtype.Text        `json:"client_token"`
	ExpiresAt     time.Time          `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
	CreatedAt     time.Time          `json:"created_at"`
	Uuid          uuid.UUID          `json:"uuid"`
	CurrentName   string             `json:"current_name"`
	AccountID     uuid.UUID          `json:"account_id"`
}

// 带 profile 联查:MC 端点的每一次令牌校验都要这个组合,
// 分两次查等于给并发刷新留了个竞态窗口。
func (q *Queries) GetMCAccessTokenWithProfile(ctx context.Context, tokenHash []byte) (GetMCAccessTokenWithProfileRow, error) {
	row := q.db.QueryRow(ctx, getMCAccessTokenWithProfile, tokenHash)
	var i GetMCAccessTokenWithProfileRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ClientToken,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.Uuid,
		&i.CurrentName,
		&i.AccountID,
	)
	return i, err
}

const getMCLoginEnabled = `-- name: GetMCLoginEnabled :one
SELECT mc_login_enabled FROM identity.account WHERE id = $1
`

func (q *Queries) GetMCLoginEnabled(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getMCLoginEnabled, id)
	var mc_login_enabled bool
	err := row.Scan(&mc_login_enabled)
	return mc_login_enabled, err
}

const getMCServer = `-- name: GetMCServer :one

SELECT id, server_id, name, shared_secret, enabled, created_at, updated_at FROM minecraft.server WHERE server_id = $1
`

// ---------------------------------------------------------------- MC 服务器
func (q *Queries) GetMCServer(ctx context.Context, serverID string) (MinecraftServer, error) {
	row := q.db.QueryRow(ctx, getMCServer, serverID)
	var i MinecraftServer
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.SharedSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMCSigningKey = `-- name: GetMCSigningKey :one
SELECT id, kid, algo, public_jwk, private_jwk_enc, status, created_at, retired_at FROM minecraft.signing_key WHERE kid = $1
`

func (q *Queries) GetMCSigningKey(ctx context.Context, kid string) (MinecraftSigningKey, error) {
	row := q.db.QueryRow(ctx, getMCSigningKey, kid)
	var i MinecraftSigningKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.Algo,
		&i.PublicJwk,
		&i.PrivateJwkEnc,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getNameHistory = `-- name: GetNameHistory :many
SELECT id, profile_id, name, changed_at, reusable_at FROM minecraft.name_history
WHERE profile_id = $1
ORDER BY changed_at DESC
`

func (q *Queries) GetNameHistory(ctx context.Context, profileID uuid.UUID) ([]MinecraftNameHistory, error) {
	rows, err := q.db.Query(ctx, getNameHistory, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinecraftNameHistory{}
	for rows.Next() {
		var i MinecraftNameHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.ChangedAt,
			&i.ReusableAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileByAccount = `-- name: GetProfileByAccount :one
SELECT id, account_id, uuid, current_name, created_at, updated_at FROM minecraft.profile WHERE account_id = $1
`

func (q *Queries) GetProfileByAccount(ctx context.Context, accountID uuid.UUID) (MinecraftProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByAccount, accountID)
	var i MinecraftProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Uuid,
		&i.CurrentName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByName = `-- name: GetProfileByName :one
SELECT id, account_id, uuid, current_name, created_at, updated_at FROM minecraft.profile WHERE current_name = $1
`

func (q *Queries) GetProfileByName(ctx context.Context, currentName string) (MinecraftProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByName, currentName)
	var i MinecraftProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Uuid,
		&i.CurrentName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUUID = `-- name: GetProfileByUUID :one
SELECT id, account_id, uuid, current_name, created_at, updated_at FROM minecraft.profile WHERE uuid = $1
`

func (q *Queries) GetProfileByUUID(ctx context.Context, argUuid uuid.UUID) (MinecraftProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByUUID, argUuid)
	var i MinecraftProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Uuid,
		&i.CurrentName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReusableNameConflict = `-- name: GetReusableNameConflict :one
SELECT id, profile_id, name, changed_at, reusable_at FROM minecraft.name_history
WHERE lower(name) = lower($1)
  AND (reusable_at IS NULL OR reusable_at > now())
ORDER BY changed_at DESC
LIMIT 1
`

// 查这个名字是否还在保留期内。reusable_at IS NULL 表示永久保留。
func (q *Queries) GetReusableNameConflict(ctx context.Context, name string) (MinecraftNameHistory, error) {
	row := q.db.QueryRow(ctx, getReusableNameConflict, name)
	var i MinecraftNameHistory
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.ChangedAt,
		&i.ReusableAt,
	)
	return i, err
}

const getServerSession = `-- name: GetServerSession :one
SELECT id, profile_id, server_id, ip, joined_at, verified_at, disconnected_at FROM minecraft.server_session WHERE server_id = $1
`

func (q *Queries) GetServerSession(ctx context.Context, serverID string) (MinecraftServerSession, error) {
	row := q.db.QueryRow(ctx, getServerSession, serverID)
	var i MinecraftServerSession
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ServerID,
		&i.Ip,
		&i.JoinedAt,
		&i.VerifiedAt,
		&i.DisconnectedAt,
	)
	return i, err
}

const insertNameHistory = `-- name: InsertNameHistory :one

INSERT INTO minecraft.name_history (profile_id, name, reusable_at)
VALUES ($1, $2, $3::timestamptz)
RETURNING id, profile_id, name, changed_at, reusable_at
`

type InsertNameHistoryParams struct {
	ProfileID  uuid.UUID          `json:"profile_id"`
	Name       string             `json:"name"`
	ReusableAt pgtype.Timestamptz `json:"reusable_at"`
}

// ---------------------------------------------------------------- 改名历史
func (q *Queries) InsertNameHistory(ctx context.Context, arg InsertNameHistoryParams) (MinecraftNameHistory, error) {
	row := q.db.QueryRow(ctx, insertNameHistory, arg.ProfileID, arg.Name, arg.ReusableAt)
	var i MinecraftNameHistory
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.ChangedAt,
		&i.ReusableAt,
	)
	return i, err
}

const listMCServers = `-- name: ListMCServers :many
SELECT id, server_id, name, shared_secret, enabled, created_at, updated_at FROM minecraft.server ORDER BY created_at
`

func (q *Queries) ListMCServers(ctx context.Context) ([]MinecraftServer, error) {
	rows, err := q.db.Query(ctx, listMCServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinecraftServer{}
	for rows.Next() {
		var i MinecraftServer
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.SharedSecret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCSigningKeys = `-- name: ListMCSigningKeys :many
SELECT id, kid, algo, public_jwk, private_jwk_enc, status, created_at, retired_at FROM minecraft.signing_key ORDER BY created_at DESC
`

func (q *Queries) ListMCSigningKeys(ctx context.Context) ([]MinecraftSigningKey, error) {
	rows, err := q.db.Query(ctx, listMCSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinecraftSigningKey{}
	for rows.Next() {
		var i MinecraftSigningKey
		if err := rows.Scan(
			&i.ID,
			&i.Kid,
			&i.Algo,
			&i.PublicJwk,
			&i.PrivateJwkEnc,
			&i.Status,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingServerSessions = `-- name: ListPendingServerSessions :many
SELECT id, profile_id, server_id, ip, joined_at, verified_at, disconnected_at FROM minecraft.server_session
WHERE profile_id = $1
  AND verified_at IS NULL
  AND joined_at > now() - $2::interval
ORDER BY joined_at DESC
LIMIT 20
`

type ListPendingServerSessionsParams struct {
	ProfileID uuid.UUID       `json:"profile_id"`
	Window    pgtype.Interval `json:"window"`
}

// 列出某玩家尚未核销、且仍在时间窗内的进服会话。
//
// hasJoined 收到的是**签名**(serverIdHash),不是原始 serverId,
// 要重算就得把该玩家的候选会话逐个试一遍。因此候选集必须小 ——
// 时间窗和「一次核销」两条约束共同把它压到个位数。
func (q *Queries) ListPendingServerSessions(ctx context.Context, arg ListPendingServerSessionsParams) ([]MinecraftServerSession, error) {
	rows, err := q.db.Query(ctx, listPendingServerSessions, arg.ProfileID, arg.Window)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinecraftServerSession{}
	for rows.Next() {
		var i MinecraftServerSession
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ServerID,
			&i.Ip,
			&i.JoinedAt,
			&i.VerifiedAt,
			&i.DisconnectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingServerSessionsBefore = `-- name: ListPendingServerSessionsBefore :many
SELECT id, profile_id, server_id, ip, joined_at, verified_at, disconnected_at FROM minecraft.server_session
WHERE profile_id = $1
  AND verified_at IS NULL
  AND joined_at >= $2::timestamptz
ORDER BY joined_at DESC
LIMIT 20
`

type ListPendingServerSessionsBeforeParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Cutoff    time.Time `json:"cutoff"`
}

// 同上,但用**调用方算好的截止时间**而不是数据库的 now()。
//
// 时间窗的判定必须用应用时钟:服务注入的是可替换的 Clock,
// 测试要靠推进它来验证过期行为;而数据库的 now() 推不动。
// 顺带消除了「数据库时钟与进程时钟漂移」带来的判定不一致。
func (q *Queries) ListPendingServerSessionsBefore(ctx context.Context, arg ListPendingServerSessionsBeforeParams) ([]MinecraftServerSession, error) {
	rows, err := q.db.Query(ctx, listPendingServerSessionsBefore, arg.ProfileID, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinecraftServerSession{}
	for rows.Next() {
		var i MinecraftServerSession
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ServerID,
			&i.Ip,
			&i.JoinedAt,
			&i.VerifiedAt,
			&i.DisconnectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilesByAccount = `-- name: ListProfilesByAccount :many
SELECT id, account_id, uuid, current_name, created_at, updated_at FROM minecraft.profile WHERE account_id = $1
`

func (q *Queries) ListProfilesByAccount(ctx context.Context, accountID uuid.UUID) ([]MinecraftProfile, error) {
	rows, err := q.db.Query(ctx, listProfilesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinecraftProfile{}
	for rows.Next() {
		var i MinecraftProfile
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Uuid,
			&i.CurrentName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markServerSessionVerified = `-- name: MarkServerSessionVerified :execrows
UPDATE minecraft.server_session SET verified_at = now()
WHERE server_id = $1 AND verified_at IS NULL
`

// 防重放:同一 serverId 只允许成功核销一次。
// 条件里带 verified_at IS NULL,第二次 hasJoined 命中 0 行。
func (q *Queries) MarkServerSessionVerified(ctx context.Context, serverID string) (int64, error) {
	result, err := q.db.Exec(ctx, markServerSessionVerified, serverID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameProfile = `-- name: RenameProfile :one
UPDATE minecraft.profile
SET current_name = $1, updated_at = now()
WHERE id = $2
RETURNING id, account_id, uuid, current_name, created_at, updated_at
`

type RenameProfileParams struct {
	CurrentName string    `json:"current_name"`
	ID          uuid.UUID `json:"id"`
}

// 改名。current_name 上的唯一索引会挡住重名 —— 这是最后一道防线,
// 上层的前置检查只是为了给出可读的错误信息。
func (q *Queries) RenameProfile(ctx context.Context, arg RenameProfileParams) (MinecraftProfile, error) {
	row := q.db.QueryRow(ctx, renameProfile, arg.CurrentName, arg.ID)
	var i MinecraftProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Uuid,
		&i.CurrentName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retireActiveMCSigningKey = `-- name: RetireActiveMCSigningKey :exec
UPDATE minecraft.signing_key
SET status = 'retired', retired_at = now()
WHERE status = 'active'
`

// 与 oidc 侧同样的理由:同一语句里改 CTE 再往带唯一索引的列插值,
// PostgreSQL 看不见 CTE 的效果,必然撞 duplicate key。拆成两条。
func (q *Queries) RetireActiveMCSigningKey(ctx context.Context) error {
	_, err := q.db.Exec(ctx, retireActiveMCSigningKey)
	return err
}

const revokeMCAccessToken = `-- name: RevokeMCAccessToken :execrows
UPDATE minecraft.access_token
SET revoked_at = now(), revoked_reason = $1::text
WHERE token_hash = $2::bytea AND revoked_at IS NULL
`

type RevokeMCAccessTokenParams struct {
	Reason    string `json:"reason"`
	TokenHash []byte `json:"token_hash"`
}

func (q *Queries) RevokeMCAccessToken(ctx context.Context, arg RevokeMCAccessTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMCAccessToken, arg.Reason, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeMCAccessTokensByProfile = `-- name: RevokeMCAccessTokensByProfile :execrows
UPDATE minecraft.access_token
SET revoked_at = now(), revoked_reason = $1::text
WHERE profile_id = $2 AND revoked_at IS NULL
`

type RevokeMCAccessTokensByProfileParams struct {
	Reason    string    `json:"reason"`
	ProfileID uuid.UUID `json:"profile_id"`
}

func (q *Queries) RevokeMCAccessTokensByProfile(ctx context.Context, arg RevokeMCAccessTokensByProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMCAccessTokensByProfile, arg.Reason, arg.ProfileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateMCAccessToken = `-- name: RotateMCAccessToken :one
WITH old AS (
    UPDATE minecraft.access_token
    SET revoked_at = now(), revoked_reason = 'refreshed'
    WHERE token_hash = $3::bytea AND revoked_at IS NULL
    RETURNING profile_id, client_token
)
INSERT INTO minecraft.access_token (token_hash, profile_id, client_token, expires_at)
SELECT $1::bytea, old.profile_id, old.client_token,
       $2::timestamptz
FROM old
RETURNING id, token_hash, profile_id, client_token, expires_at, revoked_at, revoked_reason, created_at
`

type RotateMCAccessTokenParams struct {
	NewHash   []byte    `json:"new_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	OldHash   []byte    `json:"old_hash"`
}

// 刷新:吊销旧令牌并签发新的一条,在同一条语句里完成。
//
// 分成两步的话,中间崩溃会留下「旧令牌已废、新令牌没发」的空窗,
// 玩家会被直接踢下线。
func (q *Queries) RotateMCAccessToken(ctx context.Context, arg RotateMCAccessTokenParams) (MinecraftAccessToken, error) {
	row := q.db.QueryRow(ctx, rotateMCAccessToken, arg.NewHash, arg.ExpiresAt, arg.OldHash)
	var i MinecraftAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ProfileID,
		&i.ClientToken,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const updateMCServer = `-- name: UpdateMCServer :one
UPDATE minecraft.server
SET name = $1, shared_secret = $2,
    enabled = $3::boolean, updated_at = now()
WHERE server_id = $4
RETURNING id, server_id, name, shared_secret, enabled, created_at, updated_at
`

type UpdateMCServerParams struct {
	Name         string `json:"name"`
	SharedSecret string `json:"shared_secret"`
	Enabled      bool   `json:"enabled"`
	ServerID     string `json:"server_id"`
}

func (q *Queries) UpdateMCServer(ctx context.Context, arg UpdateMCServerParams) (MinecraftServer, error) {
	row := q.db.QueryRow(ctx, updateMCServer,
		arg.Name,
		arg.SharedSecret,
		arg.Enabled,
		arg.ServerID,
	)
	var i MinecraftServer
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.SharedSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
