// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppSetting struct {
	Key       string      `json:"key"`
	Value     []byte      `json:"value"`
	UpdatedAt time.Time   `json:"updated_at"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

type IdentityAccount struct {
	ID              uuid.UUID          `json:"id"`
	Username        string             `json:"username"`
	UsernameLower   string             `json:"username_lower"`
	Email           string             `json:"email"`
	Status          string             `json:"status"`
	McLoginEnabled  bool               `json:"mc_login_enabled"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type IdentityAccountRole struct {
	AccountID uuid.UUID   `json:"account_id"`
	RoleID    uuid.UUID   `json:"role_id"`
	GrantedAt time.Time   `json:"granted_at"`
	GrantedBy pgtype.UUID `json:"granted_by"`
}

type IdentityAuditEvent struct {
	ID         int64       `json:"id"`
	OccurredAt time.Time   `json:"occurred_at"`
	AccountID  pgtype.UUID `json:"account_id"`
	Actor      string      `json:"actor"`
	Action     string      `json:"action"`
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.Text `json:"target_id"`
	Outcome    string      `json:"outcome"`
	Ip         *netip.Addr `json:"ip"`
	UserAgent  pgtype.Text `json:"user_agent"`
	Metadata   []byte      `json:"metadata"`
}

type IdentityCredential struct {
	ID             uuid.UUID          `json:"id"`
	AccountID      uuid.UUID          `json:"account_id"`
	Algo           string             `json:"algo"`
	Hash           string             `json:"hash"`
	Params         []byte             `json:"params"`
	FailedAttempts int32              `json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	ChangedAt      time.Time          `json:"changed_at"`
}

type IdentityEmailToken struct {
	ID        uuid.UUID          `json:"id"`
	AccountID uuid.UUID          `json:"account_id"`
	TokenHash []byte             `json:"token_hash"`
	Purpose   string             `json:"purpose"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type IdentityInvitation struct {
	ID        uuid.UUID          `json:"id"`
	Code      string             `json:"code"`
	Email     pgtype.Text        `json:"email"`
	MaxUses   int32              `json:"max_uses"`
	UsedCount int32              `json:"used_count"`
	ExpiresAt time.Time          `json:"expires_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt time.Time          `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type IdentityPermission struct {
	Code        string    `json:"code"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type IdentityRole struct {
	ID          uuid.UUID   `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsSystem    bool        `json:"is_system"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type IdentityRolePermission struct {
	RoleID     uuid.UUID `json:"role_id"`
	Permission string    `json:"permission"`
}

type IdentitySession struct {
	ID            uuid.UUID          `json:"id"`
	AccountID     uuid.UUID          `json:"account_id"`
	TokenHash     []byte             `json:"token_hash"`
	SsoSessionID  pgtype.UUID        `json:"sso_session_id"`
	CreatedAt     time.Time          `json:"created_at"`
	LastSeenAt    time.Time          `json:"last_seen_at"`
	ExpiresAt     time.Time          `json:"expires_at"`
	IdleExpiresAt time.Time          `json:"idle_expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason  pgtype.Text        `json:"revoke_reason"`
	Ip            *netip.Addr        `json:"ip"`
	UserAgent     pgtype.Text        `json:"user_agent"`
}

type MinecraftAccessToken struct {
	ID            uuid.UUID          `json:"id"`
	TokenHash     []byte             `json:"token_hash"`
	ProfileID     uuid.UUID          `json:"profile_id"`
	ClientToken   pgtype.Text        `json:"client_token"`
	ExpiresAt     time.Time          `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
	CreatedAt     time.Time          `json:"created_at"`
}

type MinecraftAvatar struct {
	ProfileID  uuid.UUID `json:"profile_id"`
	Hash       string    `json:"hash"`
	RenderedAt time.Time `json:"rendered_at"`
}

type MinecraftExternalBinding struct {
	ID             uuid.UUID `json:"id"`
	ProfileID      uuid.UUID `json:"profile_id"`
	Provider       string    `json:"provider"`
	ExternalUserID string    `json:"external_user_id"`
	BaseUrl        string    `json:"base_url"`
	Enabled        bool      `json:"enabled"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type MinecraftNameHistory struct {
	ID         uuid.UUID          `json:"id"`
	ProfileID  uuid.UUID          `json:"profile_id"`
	Name       string             `json:"name"`
	ChangedAt  time.Time          `json:"changed_at"`
	ReusableAt pgtype.Timestamptz `json:"reusable_at"`
}

type MinecraftProfile struct {
	ID          uuid.UUID `json:"id"`
	AccountID   uuid.UUID `json:"account_id"`
	Uuid        uuid.UUID `json:"uuid"`
	CurrentName string    `json:"current_name"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type MinecraftProfileTexture struct {
	ProfileID uuid.UUID `json:"profile_id"`
	TextureID uuid.UUID `json:"texture_id"`
	Type      string    `json:"type"`
	UpdatedAt time.Time `json:"updated_at"`
}

type MinecraftServer struct {
	ID           uuid.UUID `json:"id"`
	ServerID     string    `json:"server_id"`
	Name         string    `json:"name"`
	SharedSecret string    `json:"shared_secret"`
	Enabled      bool      `json:"enabled"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type MinecraftServerSession struct {
	ID             uuid.UUID          `json:"id"`
	ProfileID      uuid.UUID          `json:"profile_id"`
	ServerID       string             `json:"server_id"`
	Ip             *netip.Addr        `json:"ip"`
	JoinedAt       time.Time          `json:"joined_at"`
	VerifiedAt     pgtype.Timestamptz `json:"verified_at"`
	DisconnectedAt pgtype.Timestamptz `json:"disconnected_at"`
}

type MinecraftSigningKey struct {
	ID            uuid.UUID          `json:"id"`
	Kid           string             `json:"kid"`
	Algo          string             `json:"algo"`
	PublicJwk     []byte             `json:"public_jwk"`
	PrivateJwkEnc []byte             `json:"private_jwk_enc"`
	Status        string             `json:"status"`
	CreatedAt     time.Time          `json:"created_at"`
	RetiredAt     pgtype.Timestamptz `json:"retired_at"`
}

type MinecraftTexture struct {
	ID         uuid.UUID `json:"id"`
	Hash       string    `json:"hash"`
	Type       string    `json:"type"`
	Size       int32     `json:"size"`
	Width      int32     `json:"width"`
	Height     int32     `json:"height"`
	Mime       string    `json:"mime"`
	RefCount   int32     `json:"ref_count"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	LastUsedAt time.Time `json:"last_used_at"`
}

type OidcAccessToken struct {
	ID            uuid.UUID          `json:"id"`
	TokenHash     []byte             `json:"token_hash"`
	Signature     []byte             `json:"signature"`
	ClientID      string             `json:"client_id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	Scopes        []string           `json:"scopes"`
	Session       []byte             `json:"session"`
	Request       []byte             `json:"request"`
	ExpiresAt     time.Time          `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
	CreatedAt     time.Time          `json:"created_at"`
}

type OidcAuthorizationCode struct {
	ID                  uuid.UUID          `json:"id"`
	CodeHash            []byte             `json:"code_hash"`
	CodeSignature       []byte             `json:"code_signature"`
	ClientID            string             `json:"client_id"`
	AccountID           uuid.UUID          `json:"account_id"`
	RedirectUri         string             `json:"redirect_uri"`
	Scopes              []string           `json:"scopes"`
	Nonce               pgtype.Text        `json:"nonce"`
	CodeChallenge       string             `json:"code_challenge"`
	CodeChallengeMethod string             `json:"code_challenge_method"`
	Session             []byte             `json:"session"`
	Request             []byte             `json:"request"`
	ExpiresAt           time.Time          `json:"expires_at"`
	UsedAt              pgtype.Timestamptz `json:"used_at"`
	CreatedAt           time.Time          `json:"created_at"`
}

type OidcClient struct {
	ID                   uuid.UUID       `json:"id"`
	ClientID             string          `json:"client_id"`
	ClientSecretHash     pgtype.Text     `json:"client_secret_hash"`
	Name                 string          `json:"name"`
	Description          pgtype.Text     `json:"description"`
	RedirectUris         []string        `json:"redirect_uris"`
	GrantTypes           []string        `json:"grant_types"`
	Scopes               []string        `json:"scopes"`
	RequirePkce          bool            `json:"require_pkce"`
	AccessTokenTtl       pgtype.Interval `json:"access_token_ttl"`
	RefreshTokenTtl      pgtype.Interval `json:"refresh_token_ttl"`
	AuthorizationCodeTtl pgtype.Interval `json:"authorization_code_ttl"`
	Status               string          `json:"status"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
}

type OidcConsent struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
	ClientID  string    `json:"client_id"`
	Scopes    []string  `json:"scopes"`
	SessionID string    `json:"session_id"`
	GrantedAt time.Time `json:"granted_at"`
	Session   []byte    `json:"session"`
}

type OidcDeviceCode struct {
	ID             uuid.UUID          `json:"id"`
	DeviceCodeHash []byte             `json:"device_code_hash"`
	UserCodeHash   []byte             `json:"user_code_hash"`
	ClientID       string             `json:"client_id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	Scopes         []string           `json:"scopes"`
	Status         string             `json:"status"`
	Session        []byte             `json:"session"`
	Request        []byte             `json:"request"`
	ExpiresAt      time.Time          `json:"expires_at"`
	LastPolledAt   pgtype.Timestamptz `json:"last_polled_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

type OidcPushedAuthorizationRequest struct {
	ID             uuid.UUID          `json:"id"`
	RequestUriHash []byte             `json:"request_uri_hash"`
	ClientID       string             `json:"client_id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	Request        []byte             `json:"request"`
	ExpiresAt      time.Time          `json:"expires_at"`
	UsedAt         pgtype.Timestamptz `json:"used_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

type OidcRefreshToken struct {
	ID            uuid.UUID          `json:"id"`
	TokenHash     []byte             `json:"token_hash"`
	Signature     []byte             `json:"signature"`
	ClientID      string             `json:"client_id"`
	AccountID     uuid.UUID          `json:"account_id"`
	Scopes        []string           `json:"scopes"`
	RotatedFrom   pgtype.UUID        `json:"rotated_from"`
	Session       []byte             `json:"session"`
	Request       []byte             `json:"request"`
	ExpiresAt     time.Time          `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
	CreatedAt     time.Time          `json:"created_at"`
}

type OidcSigningKey struct {
	ID            uuid.UUID          `json:"id"`
	Kid           string             `json:"kid"`
	Algo          string             `json:"algo"`
	PublicJwk     []byte             `json:"public_jwk"`
	PrivateJwkEnc []byte             `json:"private_jwk_enc"`
	Status        string             `json:"status"`
	CreatedAt     time.Time          `json:"created_at"`
	RetiredAt     pgtype.Timestamptz `json:"retired_at"`
}
