// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveDeviceCode = `-- name: ApproveDeviceCode :one
UPDATE oidc.device_code
SET status = 'approved',
    account_id = $1,
    session = $2::jsonb,
    request = $3::jsonb
WHERE id = $4 AND status = 'pending'
RETURNING id, device_code_hash, user_code_hash, client_id, account_id, scopes, status, session, request, expires_at, last_polled_at, created_at
`

type ApproveDeviceCodeParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Session   []byte      `json:"session"`
	Request   []byte      `json:"request"`
	ID        uuid.UUID   `json:"id"`
}

// 用户在浏览器端批准。approved 之前轮询令牌一律返回 authorization_pending。
func (q *Queries) ApproveDeviceCode(ctx context.Context, arg ApproveDeviceCodeParams) (OidcDeviceCode, error) {
	row := q.db.QueryRow(ctx, approveDeviceCode,
		arg.AccountID,
		arg.Session,
		arg.Request,
		arg.ID,
	)
	var i OidcDeviceCode
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.ClientID,
		&i.AccountID,
		&i.Scopes,
		&i.Status,
		&i.Session,
		&i.Request,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumeDeviceCode = `-- name: ConsumeDeviceCode :execrows
UPDATE oidc.device_code SET status = 'consumed' WHERE id = $1
`

func (q *Queries) ConsumeDeviceCode(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeDeviceCode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumePAR = `-- name: ConsumePAR :execrows
UPDATE oidc.pushed_authorization_request SET used_at = now()
WHERE request_uri_hash = $1::bytea AND used_at IS NULL
`

// 一次性消费:PAR 的 request_uri 用掉即作废。
func (q *Queries) ConsumePAR(ctx context.Context, requestUriHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, consumePAR, requestUriHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countClients = `-- name: CountClients :one
SELECT count(*) FROM oidc.client
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL
       OR client_id LIKE $2 OR name LIKE $2)
`

type CountClientsParams struct {
	Status pgtype.Text `json:"status"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) CountClients(ctx context.Context, arg CountClientsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClients, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccessToken = `-- name: CreateAccessToken :one

INSERT INTO oidc.access_token (
    token_hash, signature, client_id, account_id, scopes, session, request, expires_at)
VALUES (
    $1::bytea,
    $2::bytea,
    $3,
    $4::uuid,
    $5::text[],
    $6::jsonb,
    $7::jsonb,
    $8::timestamptz)
RETURNING id, token_hash, signature, client_id, account_id, scopes, session, request, expires_at, revoked_at, revoked_reason, created_at
`

type CreateAccessTokenParams struct {
	TokenHash []byte      `json:"token_hash"`
	Signature []byte      `json:"signature"`
	ClientID  string      `json:"client_id"`
	AccountID pgtype.UUID `json:"account_id"`
	Scopes    []string    `json:"scopes"`
	Session   []byte      `json:"session"`
	Request   []byte      `json:"request"`
	ExpiresAt time.Time   `json:"expires_at"`
}

// ---------------------------------------------------------------- 访问令牌
func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (OidcAccessToken, error) {
	row := q.db.QueryRow(ctx, createAccessToken,
		arg.TokenHash,
		arg.Signature,
		arg.ClientID,
		arg.AccountID,
		arg.Scopes,
		arg.Session,
		arg.Request,
		arg.ExpiresAt,
	)
	var i OidcAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Signature,
		&i.ClientID,
		&i.AccountID,
		&i.Scopes,
		&i.Session,
		&i.Request,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthorizationCode = `-- name: CreateAuthorizationCode :one

INSERT INTO oidc.authorization_code (
    code_hash, code_signature, client_id, account_id, redirect_uri, scopes,
    nonce, code_challenge, code_challenge_method, session, request, expires_at)
VALUES (
    $1::bytea,
    $2::bytea,
    $3,
    $4,
    $5,
    $6::text[],
    $7::text,
    $8::text,
    $9::text,
    $10::jsonb,
    $11::jsonb,
    $12::timestamptz)
RETURNING id, code_hash, code_signature, client_id, account_id, redirect_uri, scopes, nonce, code_challenge, code_challenge_method, session, request, expires_at, used_at, created_at
`

type CreateAuthorizationCodeParams struct {
	CodeHash            []byte      `json:"code_hash"`
	CodeSignature       []byte      `json:"code_signature"`
	ClientID            string      `json:"client_id"`
	AccountID           uuid.UUID   `json:"account_id"`
	RedirectUri         string      `json:"redirect_uri"`
	Scopes              []string    `json:"scopes"`
	Nonce               pgtype.Text `json:"nonce"`
	CodeChallenge       pgtype.Text `json:"code_challenge"`
	CodeChallengeMethod pgtype.Text `json:"code_challenge_method"`
	Session             []byte      `json:"session"`
	Request             []byte      `json:"request"`
	ExpiresAt           time.Time   `json:"expires_at"`
}

// ---------------------------------------------------------------- 授权码
func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (OidcAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createAuthorizationCode,
		arg.CodeHash,
		arg.CodeSignature,
		arg.ClientID,
		arg.AccountID,
		arg.RedirectUri,
		arg.Scopes,
		arg.Nonce,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.Session,
		arg.Request,
		arg.ExpiresAt,
	)
	var i OidcAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.CodeSignature,
		&i.ClientID,
		&i.AccountID,
		&i.RedirectUri,
		&i.Scopes,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Session,
		&i.Request,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO oidc.client (
    client_id, client_secret_hash, name, description, redirect_uris,
    grant_types, scopes, require_pkce, access_token_ttl, refresh_token_ttl,
    authorization_code_ttl)
VALUES (
    $1,
    $2::text,
    $3,
    $4::text,
    $5::text[],
    $6::text[],
    $7::text[],
    $8::boolean,
    $9::interval,
    $10::interval,
    $11::interval)
RETURNING id, client_id, client_secret_hash, name, description, redirect_uris, grant_types, scopes, require_pkce, access_token_ttl, refresh_token_ttl, authorization_code_ttl, status, created_at, updated_at
`

type CreateClientParams struct {
	ClientID             string          `json:"client_id"`
	ClientSecretHash     pgtype.Text     `json:"client_secret_hash"`
	Name                 string          `json:"name"`
	Description          pgtype.Text     `json:"description"`
	RedirectUris         []string        `json:"redirect_uris"`
	GrantTypes           []string        `json:"grant_types"`
	Scopes               []string        `json:"scopes"`
	RequirePkce          bool            `json:"require_pkce"`
	AccessTokenTtl       pgtype.Interval `json:"access_token_ttl"`
	RefreshTokenTtl      pgtype.Interval `json:"refresh_token_ttl"`
	AuthorizationCodeTtl pgtype.Interval `json:"authorization_code_ttl"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (OidcClient, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.Name,
		arg.Description,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.Scopes,
		arg.RequirePkce,
		arg.AccessTokenTtl,
		arg.RefreshTokenTtl,
		arg.AuthorizationCodeTtl,
	)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.Description,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.Scopes,
		&i.RequirePkce,
		&i.AccessTokenTtl,
		&i.RefreshTokenTtl,
		&i.AuthorizationCodeTtl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClientAssertion = `-- name: CreateClientAssertion :one

INSERT INTO oidc.client_assertion (jti, expires_at)
VALUES ($1, $2::timestamptz)
ON CONFLICT (jti) DO NOTHING
RETURNING jti
`

type CreateClientAssertionParams struct {
	Jti       string    `json:"jti"`
	ExpiresAt time.Time `json:"expires_at"`
}

// ---------------------------------------------------------------- 客户端断言 JWT
// 防重放:同一个 jti 只允许用一次。
func (q *Queries) CreateClientAssertion(ctx context.Context, arg CreateClientAssertionParams) (string, error) {
	row := q.db.QueryRow(ctx, createClientAssertion, arg.Jti, arg.ExpiresAt)
	var jti string
	err := row.Scan(&jti)
	return jti, err
}

const createDeviceCode = `-- name: CreateDeviceCode :one

INSERT INTO oidc.device_code (
    device_code_hash, user_code_hash, client_id, account_id, scopes,
    session, request, expires_at)
VALUES (
    $1::bytea,
    $2::bytea,
    $3,
    $4::uuid,
    $5::text[],
    $6::jsonb,
    $7::jsonb,
    $8::timestamptz)
RETURNING id, device_code_hash, user_code_hash, client_id, account_id, scopes, status, session, request, expires_at, last_polled_at, created_at
`

type CreateDeviceCodeParams struct {
	DeviceCodeHash []byte      `json:"device_code_hash"`
	UserCodeHash   []byte      `json:"user_code_hash"`
	ClientID       string      `json:"client_id"`
	AccountID      pgtype.UUID `json:"account_id"`
	Scopes         []string    `json:"scopes"`
	Session        []byte      `json:"session"`
	Request        []byte      `json:"request"`
	ExpiresAt      time.Time   `json:"expires_at"`
}

// ---------------------------------------------------------------- 设备码(RFC 8628)
func (q *Queries) CreateDeviceCode(ctx context.Context, arg CreateDeviceCodeParams) (OidcDeviceCode, error) {
	row := q.db.QueryRow(ctx, createDeviceCode,
		arg.DeviceCodeHash,
		arg.UserCodeHash,
		arg.ClientID,
		arg.AccountID,
		arg.Scopes,
		arg.Session,
		arg.Request,
		arg.ExpiresAt,
	)
	var i OidcDeviceCode
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.ClientID,
		&i.AccountID,
		&i.Scopes,
		&i.Status,
		&i.Session,
		&i.Request,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPAR = `-- name: CreatePAR :one

INSERT INTO oidc.pushed_authorization_request (
    request_uri_hash, client_id, account_id, request, expires_at)
VALUES (
    $1::bytea,
    $2,
    $3::uuid,
    $4::jsonb,
    $5::timestamptz)
RETURNING id, request_uri_hash, client_id, account_id, request, expires_at, used_at, created_at
`

type CreatePARParams struct {
	RequestUriHash []byte      `json:"request_uri_hash"`
	ClientID       string      `json:"client_id"`
	AccountID      pgtype.UUID `json:"account_id"`
	Request        []byte      `json:"request"`
	ExpiresAt      time.Time   `json:"expires_at"`
}

// ---------------------------------------------------------------- PAR(RFC 9126)
func (q *Queries) CreatePAR(ctx context.Context, arg CreatePARParams) (OidcPushedAuthorizationRequest, error) {
	row := q.db.QueryRow(ctx, createPAR,
		arg.RequestUriHash,
		arg.ClientID,
		arg.AccountID,
		arg.Request,
		arg.ExpiresAt,
	)
	var i OidcPushedAuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.RequestUriHash,
		&i.ClientID,
		&i.AccountID,
		&i.Request,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPKCERequest = `-- name: CreatePKCERequest :one

INSERT INTO oidc.pkce_request (signature, challenge, challenge_method, session, request)
VALUES (
    $1::bytea,
    $2,
    $3,
    $4::jsonb,
    $5::jsonb)
RETURNING signature, challenge, challenge_method, session, request, created_at
`

type CreatePKCERequestParams struct {
	Signature       []byte `json:"signature"`
	Challenge       string `json:"challenge"`
	ChallengeMethod string `json:"challenge_method"`
	Session         []byte `json:"session"`
	Request         []byte `json:"request"`
}

// ---------------------------------------------------------------- PKCE 会话
func (q *Queries) CreatePKCERequest(ctx context.Context, arg CreatePKCERequestParams) (OidcPkceRequest, error) {
	row := q.db.QueryRow(ctx, createPKCERequest,
		arg.Signature,
		arg.Challenge,
		arg.ChallengeMethod,
		arg.Session,
		arg.Request,
	)
	var i OidcPkceRequest
	err := row.Scan(
		&i.Signature,
		&i.Challenge,
		&i.ChallengeMethod,
		&i.Session,
		&i.Request,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO oidc.refresh_token (
    token_hash, signature, client_id, account_id, scopes, rotated_from,
    session, request, expires_at)
VALUES (
    $1::bytea,
    $2::bytea,
    $3,
    $4,
    $5::text[],
    $6::uuid,
    $7::jsonb,
    $8::jsonb,
    $9::timestamptz)
RETURNING id, token_hash, signature, client_id, account_id, scopes, rotated_from, session, request, expires_at, revoked_at, revoked_reason, created_at
`

type CreateRefreshTokenParams struct {
	TokenHash   []byte      `json:"token_hash"`
	Signature   []byte      `json:"signature"`
	ClientID    string      `json:"client_id"`
	AccountID   uuid.UUID   `json:"account_id"`
	Scopes      []string    `json:"scopes"`
	RotatedFrom pgtype.UUID `json:"rotated_from"`
	Session     []byte      `json:"session"`
	Request     []byte      `json:"request"`
	ExpiresAt   time.Time   `json:"expires_at"`
}

// ---------------------------------------------------------------- 刷新令牌
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (OidcRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.TokenHash,
		arg.Signature,
		arg.ClientID,
		arg.AccountID,
		arg.Scopes,
		arg.RotatedFrom,
		arg.Session,
		arg.Request,
		arg.ExpiresAt,
	)
	var i OidcRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Signature,
		&i.ClientID,
		&i.AccountID,
		&i.Scopes,
		&i.RotatedFrom,
		&i.Session,
		&i.Request,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const createSigningKey = `-- name: CreateSigningKey :one
INSERT INTO oidc.signing_key (kid, algo, public_jwk, private_jwk_enc, status)
VALUES ($1, $2, $3::jsonb,
        $4::bytea, 'active')
RETURNING id, kid, algo, public_jwk, private_jwk_enc, status, created_at, retired_at
`

type CreateSigningKeyParams struct {
	Kid           string `json:"kid"`
	Algo          string `json:"algo"`
	PublicJwk     []byte `json:"public_jwk"`
	PrivateJwkEnc []byte `json:"private_jwk_enc"`
}

// 轮换第二步:插入新的 active 密钥。
//
// 必须与上一步分成两条语句:idx_signing_key_active 是 status 列上的
// 唯一索引,而同一条语句里的数据修改 CTE 对该索引的检查不可见 ——
// 合成一条会稳定撞上 duplicate key。
func (q *Queries) CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) (OidcSigningKey, error) {
	row := q.db.QueryRow(ctx, createSigningKey,
		arg.Kid,
		arg.Algo,
		arg.PublicJwk,
		arg.PrivateJwkEnc,
	)
	var i OidcSigningKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.Algo,
		&i.PublicJwk,
		&i.PrivateJwkEnc,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :execrows
DELETE FROM oidc.client WHERE client_id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, clientID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClient, clientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteConsent = `-- name: DeleteConsent :execrows
DELETE FROM oidc.consent WHERE account_id = $1 AND client_id = $2
`

type DeleteConsentParams struct {
	AccountID uuid.UUID `json:"account_id"`
	ClientID  string    `json:"client_id"`
}

func (q *Queries) DeleteConsent(ctx context.Context, arg DeleteConsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConsent, arg.AccountID, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAccessTokens = `-- name: DeleteExpiredAccessTokens :execrows
DELETE FROM oidc.access_token
WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredAccessTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAccessTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAuthorizationCodes = `-- name: DeleteExpiredAuthorizationCodes :execrows
DELETE FROM oidc.authorization_code
WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredAuthorizationCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthorizationCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredClientAssertions = `-- name: DeleteExpiredClientAssertions :execrows
DELETE FROM oidc.client_assertion WHERE expires_at < now() - interval '1 hour'
`

func (q *Queries) DeleteExpiredClientAssertions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredClientAssertions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredDeviceCodes = `-- name: DeleteExpiredDeviceCodes :execrows
DELETE FROM oidc.device_code WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredDeviceCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredDeviceCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredPAR = `-- name: DeleteExpiredPAR :execrows
DELETE FROM oidc.pushed_authorization_request
WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredPAR(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPAR)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredPKCERequests = `-- name: DeleteExpiredPKCERequests :execrows
DELETE FROM oidc.pkce_request WHERE created_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredPKCERequests(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPKCERequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM oidc.refresh_token
WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePKCERequest = `-- name: DeletePKCERequest :execrows
DELETE FROM oidc.pkce_request WHERE signature = $1::bytea
`

func (q *Queries) DeletePKCERequest(ctx context.Context, signature []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deletePKCERequest, signature)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const denyDeviceCode = `-- name: DenyDeviceCode :execrows
UPDATE oidc.device_code SET status = 'denied'
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) DenyDeviceCode(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, denyDeviceCode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccessTokenByHash = `-- name: GetAccessTokenByHash :one
SELECT id, token_hash, signature, client_id, account_id, scopes, session, request, expires_at, revoked_at, revoked_reason, created_at FROM oidc.access_token WHERE token_hash = $1::bytea
`

func (q *Queries) GetAccessTokenByHash(ctx context.Context, tokenHash []byte) (OidcAccessToken, error) {
	row := q.db.QueryRow(ctx, getAccessTokenByHash, tokenHash)
	var i OidcAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Signature,
		&i.ClientID,
		&i.AccountID,
		&i.Scopes,
		&i.Session,
		&i.Request,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getAccessTokenBySignature = `-- name: GetAccessTokenBySignature :one
SELECT id, token_hash, signature, client_id, account_id, scopes, session, request, expires_at, revoked_at, revoked_reason, created_at FROM oidc.access_token WHERE signature = $1::bytea
`

func (q *Queries) GetAccessTokenBySignature(ctx context.Context, signature []byte) (OidcAccessToken, error) {
	row := q.db.QueryRow(ctx, getAccessTokenBySignature, signature)
	var i OidcAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Signature,
		&i.ClientID,
		&i.AccountID,
		&i.Scopes,
		&i.Session,
		&i.Request,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSigningKey = `-- name: GetActiveSigningKey :one

SELECT id, kid, algo, public_jwk, private_jwk_enc, status, created_at, retired_at FROM oidc.signing_key WHERE status = 'active'
`

// ---------------------------------------------------------------- 签名密钥
func (q *Queries) GetActiveSigningKey(ctx context.Context) (OidcSigningKey, error) {
	row := q.db.QueryRow(ctx, getActiveSigningKey)
	var i OidcSigningKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.Algo,
		&i.PublicJwk,
		&i.PrivateJwkEnc,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getAuthorizationCodeByHash = `-- name: GetAuthorizationCodeByHash :one
SELECT id, code_hash, code_signature, client_id, account_id, redirect_uri, scopes, nonce, code_challenge, code_challenge_method, session, request, expires_at, used_at, created_at FROM oidc.authorization_code WHERE code_hash = $1::bytea
`

func (q *Queries) GetAuthorizationCodeByHash(ctx context.Context, codeHash []byte) (OidcAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getAuthorizationCodeByHash, codeHash)
	var i OidcAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.CodeSignature,
		&i.ClientID,
		&i.AccountID,
		&i.RedirectUri,
		&i.Scopes,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Session,
		&i.Request,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getClient = `-- name: GetClient :one
SELECT id, client_id, client_secret_hash, name, description, redirect_uris, grant_types, scopes, require_pkce, access_token_ttl, refresh_token_ttl, authorization_code_ttl, status, created_at, updated_at FROM oidc.client WHERE client_id = $1
`

func (q *Queries) GetClient(ctx context.Context, clientID string) (OidcClient, error) {
	row := q.db.QueryRow(ctx, getClient, clientID)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.Description,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.Scopes,
		&i.RequirePkce,
		&i.AccessTokenTtl,
		&i.RefreshTokenTtl,
		&i.AuthorizationCodeTtl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConsent = `-- name: GetConsent :one
SELECT id, account_id, client_id, scopes, session_id, granted_at, session FROM oidc.consent WHERE account_id = $1 AND client_id = $2
`

type GetConsentParams struct {
	AccountID uuid.UUID `json:"account_id"`
	ClientID  string    `json:"client_id"`
}

func (q *Queries) GetConsent(ctx context.Context, arg GetConsentParams) (OidcConsent, error) {
	row := q.db.QueryRow(ctx, getConsent, arg.AccountID, arg.ClientID)
	var i OidcConsent
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientID,
		&i.Scopes,
		&i.SessionID,
		&i.GrantedAt,
		&i.Session,
	)
	return i, err
}

const getDeviceCodeByDeviceHash = `-- name: GetDeviceCodeByDeviceHash :one
SELECT id, device_code_hash, user_code_hash, client_id, account_id, scopes, status, session, request, expires_at, last_polled_at, created_at FROM oidc.device_code WHERE device_code_hash = $1::bytea
`

func (q *Queries) GetDeviceCodeByDeviceHash(ctx context.Context, deviceCodeHash []byte) (OidcDeviceCode, error) {
	row := q.db.QueryRow(ctx, getDeviceCodeByDeviceHash, deviceCodeHash)
	var i OidcDeviceCode
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.ClientID,
		&i.AccountID,
		&i.Scopes,
		&i.Status,
		&i.Session,
		&i.Request,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceCodeByUserHash = `-- name: GetDeviceCodeByUserHash :one
SELECT id, device_code_hash, user_code_hash, client_id, account_id, scopes, status, session, request, expires_at, last_polled_at, created_at FROM oidc.device_code WHERE user_code_hash = $1::bytea
`

func (q *Queries) GetDeviceCodeByUserHash(ctx context.Context, userCodeHash []byte) (OidcDeviceCode, error) {
	row := q.db.QueryRow(ctx, getDeviceCodeByUserHash, userCodeHash)
	var i OidcDeviceCode
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.ClientID,
		&i.AccountID,
		&i.Scopes,
		&i.Status,
		&i.Session,
		&i.Request,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPAR = `-- name: GetPAR :one
SELECT id, request_uri_hash, client_id, account_id, request, expires_at, used_at, created_at FROM oidc.pushed_authorization_request
WHERE request_uri_hash = $1::bytea
  AND used_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetPAR(ctx context.Context, requestUriHash []byte) (OidcPushedAuthorizationRequest, error) {
	row := q.db.QueryRow(ctx, getPAR, requestUriHash)
	var i OidcPushedAuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.RequestUriHash,
		&i.ClientID,
		&i.AccountID,
		&i.Request,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPKCERequest = `-- name: GetPKCERequest :one
SELECT signature, challenge, challenge_method, session, request, created_at FROM oidc.pkce_request WHERE signature = $1::bytea
`

func (q *Queries) GetPKCERequest(ctx context.Context, signature []byte) (OidcPkceRequest, error) {
	row := q.db.QueryRow(ctx, getPKCERequest, signature)
	var i OidcPkceRequest
	err := row.Scan(
		&i.Signature,
		&i.Challenge,
		&i.ChallengeMethod,
		&i.Session,
		&i.Request,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, token_hash, signature, client_id, account_id, scopes, rotated_from, session, request, expires_at, revoked_at, revoked_reason, created_at FROM oidc.refresh_token WHERE token_hash = $1::bytea
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (OidcRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i OidcRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Signature,
		&i.ClientID,
		&i.AccountID,
		&i.Scopes,
		&i.RotatedFrom,
		&i.Session,
		&i.Request,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenBySignature = `-- name: GetRefreshTokenBySignature :one
SELECT id, token_hash, signature, client_id, account_id, scopes, rotated_from, session, request, expires_at, revoked_at, revoked_reason, created_at FROM oidc.refresh_token WHERE signature = $1::bytea
`

func (q *Queries) GetRefreshTokenBySignature(ctx context.Context, signature []byte) (OidcRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenBySignature, signature)
	var i OidcRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Signature,
		&i.ClientID,
		&i.AccountID,
		&i.Scopes,
		&i.RotatedFrom,
		&i.Session,
		&i.Request,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getSigningKey = `-- name: GetSigningKey :one
SELECT id, kid, algo, public_jwk, private_jwk_enc, status, created_at, retired_at FROM oidc.signing_key WHERE kid = $1
`

func (q *Queries) GetSigningKey(ctx context.Context, kid string) (OidcSigningKey, error) {
	row := q.db.QueryRow(ctx, getSigningKey, kid)
	var i OidcSigningKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.Algo,
		&i.PublicJwk,
		&i.PrivateJwkEnc,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const invalidateAuthorizationCode = `-- name: InvalidateAuthorizationCode :execrows
UPDATE oidc.authorization_code SET used_at = now()
WHERE code_hash = $1::bytea AND used_at IS NULL
`

// 核销授权码。条件里带 used_at IS NULL,天然防重放:
// 同一个码换第二次令牌会命中 0 行。
func (q *Queries) InvalidateAuthorizationCode(ctx context.Context, codeHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateAuthorizationCode, codeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listClients = `-- name: ListClients :many
SELECT id, client_id, client_secret_hash, name, description, redirect_uris, grant_types, scopes, require_pkce, access_token_ttl, refresh_token_ttl, authorization_code_ttl, status, created_at, updated_at FROM oidc.client
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL
       OR client_id LIKE $2 OR name LIKE $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListClientsParams struct {
	Status pgtype.Text `json:"status"`
	Search pgtype.Text `json:"search"`
	Offset int32       `json:"offset"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]OidcClient, error) {
	rows, err := q.db.Query(ctx, listClients,
		arg.Status,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcClient{}
	for rows.Next() {
		var i OidcClient
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientSecretHash,
			&i.Name,
			&i.Description,
			&i.RedirectUris,
			&i.GrantTypes,
			&i.Scopes,
			&i.RequirePkce,
			&i.AccessTokenTtl,
			&i.RefreshTokenTtl,
			&i.AuthorizationCodeTtl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSigningKeys = `-- name: ListSigningKeys :many
SELECT id, kid, algo, public_jwk, private_jwk_enc, status, created_at, retired_at FROM oidc.signing_key ORDER BY created_at DESC
`

func (q *Queries) ListSigningKeys(ctx context.Context) ([]OidcSigningKey, error) {
	rows, err := q.db.Query(ctx, listSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcSigningKey{}
	for rows.Next() {
		var i OidcSigningKey
		if err := rows.Scan(
			&i.ID,
			&i.Kid,
			&i.Algo,
			&i.PublicJwk,
			&i.PrivateJwkEnc,
			&i.Status,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireActiveSigningKey = `-- name: RetireActiveSigningKey :exec
UPDATE oidc.signing_key
SET status = 'retired', retired_at = now()
WHERE status = 'active'
`

// 轮换第一步:把当前 active 密钥降级为 retired。
//
// 旧密钥**不删除** —— 已经发出的令牌还在用它签名,删掉会让存量令牌
// 立刻验签失败。它继续留在 JWKS 里直到被显式 revoke。
func (q *Queries) RetireActiveSigningKey(ctx context.Context) error {
	_, err := q.db.Exec(ctx, retireActiveSigningKey)
	return err
}

const revokeAccessToken = `-- name: RevokeAccessToken :execrows
UPDATE oidc.access_token
SET revoked_at = now(), revoked_reason = $1::text
WHERE signature = $2::bytea AND revoked_at IS NULL
`

type RevokeAccessTokenParams struct {
	Reason    string `json:"reason"`
	Signature []byte `json:"signature"`
}

func (q *Queries) RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccessToken, arg.Reason, arg.Signature)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAccessTokenByHash = `-- name: RevokeAccessTokenByHash :execrows
UPDATE oidc.access_token
SET revoked_at = now(), revoked_reason = $1::text
WHERE token_hash = $2::bytea AND revoked_at IS NULL
`

type RevokeAccessTokenByHashParams struct {
	Reason    string `json:"reason"`
	TokenHash []byte `json:"token_hash"`
}

func (q *Queries) RevokeAccessTokenByHash(ctx context.Context, arg RevokeAccessTokenByHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccessTokenByHash, arg.Reason, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAccessTokensByAccount = `-- name: RevokeAccessTokensByAccount :execrows
UPDATE oidc.access_token
SET revoked_at = now(), revoked_reason = $1::text
WHERE account_id = $2::uuid AND revoked_at IS NULL
`

type RevokeAccessTokensByAccountParams struct {
	Reason    string    `json:"reason"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) RevokeAccessTokensByAccount(ctx context.Context, arg RevokeAccessTokensByAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccessTokensByAccount, arg.Reason, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAccessTokensByClient = `-- name: RevokeAccessTokensByClient :execrows
UPDATE oidc.access_token
SET revoked_at = now(), revoked_reason = $1::text
WHERE client_id = $2 AND revoked_at IS NULL
`

type RevokeAccessTokensByClientParams struct {
	Reason   string `json:"reason"`
	ClientID string `json:"client_id"`
}

func (q *Queries) RevokeAccessTokensByClient(ctx context.Context, arg RevokeAccessTokensByClientParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccessTokensByClient, arg.Reason, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokenBySignature = `-- name: RevokeRefreshTokenBySignature :execrows
UPDATE oidc.refresh_token
SET revoked_at = now(), revoked_reason = $1::text
WHERE signature = $2::bytea AND revoked_at IS NULL
`

type RevokeRefreshTokenBySignatureParams struct {
	Reason    string `json:"reason"`
	Signature []byte `json:"signature"`
}

func (q *Queries) RevokeRefreshTokenBySignature(ctx context.Context, arg RevokeRefreshTokenBySignatureParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenBySignature, arg.Reason, arg.Signature)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokenChain = `-- name: RevokeRefreshTokenChain :execrows
WITH RECURSIVE chain AS (
    SELECT id FROM oidc.refresh_token WHERE signature = $2::bytea
    UNION ALL
    SELECT rt.id FROM oidc.refresh_token rt
    JOIN chain c ON rt.rotated_from = c.id
)
UPDATE oidc.refresh_token
SET revoked_at = now(), revoked_reason = $1::text
WHERE id IN (SELECT id FROM chain) AND revoked_at IS NULL
`

type RevokeRefreshTokenChainParams struct {
	Reason    string `json:"reason"`
	Signature []byte `json:"signature"`
}

// 检测到重放时吊销整条轮换链:沿着 rotated_from 往上把祖先全部作废。
func (q *Queries) RevokeRefreshTokenChain(ctx context.Context, arg RevokeRefreshTokenChainParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenChain, arg.Reason, arg.Signature)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokensByAccount = `-- name: RevokeRefreshTokensByAccount :execrows
UPDATE oidc.refresh_token
SET revoked_at = now(), revoked_reason = $1::text
WHERE account_id = $2::uuid AND revoked_at IS NULL
`

type RevokeRefreshTokensByAccountParams struct {
	Reason    string    `json:"reason"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) RevokeRefreshTokensByAccount(ctx context.Context, arg RevokeRefreshTokensByAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokensByAccount, arg.Reason, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokensByClient = `-- name: RevokeRefreshTokensByClient :execrows
UPDATE oidc.refresh_token
SET revoked_at = now(), revoked_reason = $1::text
WHERE client_id = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokensByClientParams struct {
	Reason   string `json:"reason"`
	ClientID string `json:"client_id"`
}

func (q *Queries) RevokeRefreshTokensByClient(ctx context.Context, arg RevokeRefreshTokensByClientParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokensByClient, arg.Reason, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchDeviceCodePoll = `-- name: TouchDeviceCodePoll :exec
UPDATE oidc.device_code SET last_polled_at = now() WHERE id = $1
`

// 记录最近一次轮询,用于检测过于频繁的轮询。
func (q *Queries) TouchDeviceCodePoll(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchDeviceCodePoll, id)
	return err
}

const updateClient = `-- name: UpdateClient :one
UPDATE oidc.client
SET name = $1,
    description = $2::text,
    redirect_uris = $3::text[],
    grant_types = $4::text[],
    scopes = $5::text[],
    require_pkce = $6::boolean,
    access_token_ttl = $7::interval,
    refresh_token_ttl = $8::interval,
    authorization_code_ttl = $9::interval,
    status = $10::text
WHERE client_id = $11
RETURNING id, client_id, client_secret_hash, name, description, redirect_uris, grant_types, scopes, require_pkce, access_token_ttl, refresh_token_ttl, authorization_code_ttl, status, created_at, updated_at
`

type UpdateClientParams struct {
	Name                 string          `json:"name"`
	Description          pgtype.Text     `json:"description"`
	RedirectUris         []string        `json:"redirect_uris"`
	GrantTypes           []string        `json:"grant_types"`
	Scopes               []string        `json:"scopes"`
	RequirePkce          bool            `json:"require_pkce"`
	AccessTokenTtl       pgtype.Interval `json:"access_token_ttl"`
	RefreshTokenTtl      pgtype.Interval `json:"refresh_token_ttl"`
	AuthorizationCodeTtl pgtype.Interval `json:"authorization_code_ttl"`
	Status               string          `json:"status"`
	ClientID             string          `json:"client_id"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (OidcClient, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.Name,
		arg.Description,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.Scopes,
		arg.RequirePkce,
		arg.AccessTokenTtl,
		arg.RefreshTokenTtl,
		arg.AuthorizationCodeTtl,
		arg.Status,
		arg.ClientID,
	)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.Description,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.Scopes,
		&i.RequirePkce,
		&i.AccessTokenTtl,
		&i.RefreshTokenTtl,
		&i.AuthorizationCodeTtl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClientSecret = `-- name: UpdateClientSecret :one
UPDATE oidc.client
SET client_secret_hash = $1::text
WHERE client_id = $2
RETURNING id, client_id, client_secret_hash, name, description, redirect_uris, grant_types, scopes, require_pkce, access_token_ttl, refresh_token_ttl, authorization_code_ttl, status, created_at, updated_at
`

type UpdateClientSecretParams struct {
	ClientSecretHash string `json:"client_secret_hash"`
	ClientID         string `json:"client_id"`
}

// 轮换密钥。旧密钥立即失效,属于有意为之的破坏性变更。
func (q *Queries) UpdateClientSecret(ctx context.Context, arg UpdateClientSecretParams) (OidcClient, error) {
	row := q.db.QueryRow(ctx, updateClientSecret, arg.ClientSecretHash, arg.ClientID)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.Description,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.Scopes,
		&i.RequirePkce,
		&i.AccessTokenTtl,
		&i.RefreshTokenTtl,
		&i.AuthorizationCodeTtl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConsent = `-- name: UpsertConsent :one

INSERT INTO oidc.consent (account_id, client_id, scopes, session_id, session)
VALUES (
    $1,
    $2,
    $3::text[],
    $4,
    $5::jsonb)
ON CONFLICT (account_id, client_id) DO UPDATE
SET scopes = EXCLUDED.scopes,
    session_id = EXCLUDED.session_id,
    session = EXCLUDED.session,
    granted_at = now()
RETURNING id, account_id, client_id, scopes, session_id, granted_at, session
`

type UpsertConsentParams struct {
	AccountID uuid.UUID `json:"account_id"`
	ClientID  string    `json:"client_id"`
	Scopes    []string  `json:"scopes"`
	SessionID string    `json:"session_id"`
	Session   []byte    `json:"session"`
}

// ---------------------------------------------------------------- 同意记录
func (q *Queries) UpsertConsent(ctx context.Context, arg UpsertConsentParams) (OidcConsent, error) {
	row := q.db.QueryRow(ctx, upsertConsent,
		arg.AccountID,
		arg.ClientID,
		arg.Scopes,
		arg.SessionID,
		arg.Session,
	)
	var i OidcConsent
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientID,
		&i.Scopes,
		&i.SessionID,
		&i.GrantedAt,
		&i.Session,
	)
	return i, err
}
