// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	// 一次性使用:条件里带 used_at IS NULL,天然防重放。
	ConsumeEmailToken(ctx context.Context, tokenHash []byte) (*IdentityEmailToken, error)
	// 核销邀请码。used_count 的上限判断放在条件里,避免读改写竞态。
	// $2 是可选的邮箱绑定:邀请码绑定了邮箱时,只有该邮箱能使用。
	ConsumeInvitation(ctx context.Context, arg ConsumeInvitationParams) (*IdentityInvitation, error)
	CountAccounts(ctx context.Context, arg CountAccountsParams) (int64, error)
	CountAccountsWithRole(ctx context.Context, roleID uuid.UUID) (int64, error)
	CountActiveSessions(ctx context.Context, accountID uuid.UUID) (int64, error)
	CountAuditEvents(ctx context.Context, arg CountAuditEventsParams) (int64, error)
	// 归档任务用:统计某个时间点之前的行数。
	CountAuditEventsBefore(ctx context.Context, occurredAt time.Time) (int64, error)
	// 邮件每日发送上限(5 次/天)。
	CountEmailTokensSince(ctx context.Context, arg CountEmailTokensSinceParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (*IdentityAccount, error)
	CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (*IdentityEmailToken, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (*IdentityInvitation, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (*IdentityRole, error)
	// 只存 sha256(token),不存明文。
	CreateSession(ctx context.Context, arg CreateSessionParams) (*IdentitySession, error)
	DeleteAccount(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteExpiredEmailTokens(ctx context.Context) (int64, error)
	DeleteExpiredInvitations(ctx context.Context) (int64, error)
	// 后台清理任务用:删除已过期或已吊销超过 30 天的会话。
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	// 内置角色不可删。返回 0 行表示「角色不存在」或「是内置角色」,由服务层区分。
	DeleteRole(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteSetting(ctx context.Context, key string) (int64, error)
	// 导出 CSV 用:流式分页,不设上限,但仍走同一组过滤条件。
	ExportAuditEvents(ctx context.Context, arg ExportAuditEventsParams) ([]*IdentityAuditEvent, error)
	// 邮箱唯一性按 lower(email) 判断(变更 C-10),登录/找回密码都走这里。
	GetAccountByEmail(ctx context.Context, lower string) (*IdentityAccount, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (*IdentityAccount, error)
	GetAccountByUsername(ctx context.Context, usernameLower string) (*IdentityAccount, error)
	// 会话校验是最高频查询:只看未吊销、未过期的行。
	GetActiveSessionByTokenHash(ctx context.Context, tokenHash []byte) (*IdentitySession, error)
	GetCredential(ctx context.Context, arg GetCredentialParams) (*IdentityCredential, error)
	// 只取未使用且未过期的。校验和标记使用在同一个事务里完成。
	GetEmailTokenByHash(ctx context.Context, tokenHash []byte) (*IdentityEmailToken, error)
	GetInvitationByCode(ctx context.Context, code string) (*IdentityInvitation, error)
	// 邮件重发冷却:看最近一次发信时间。
	GetLastEmailToken(ctx context.Context, arg GetLastEmailTokenParams) (*IdentityEmailToken, error)
	GetPermission(ctx context.Context, code string) (*IdentityPermission, error)
	GetRoleByCode(ctx context.Context, code string) (*IdentityRole, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (*IdentityRole, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (*IdentitySession, error)
	// 全局登出:把同一 SSO 会话下的所有终端用户会话一起吊销。
	GetSessionBySSOID(ctx context.Context, ssoSessionID pgtype.UUID) ([]*IdentitySession, error)
	GetSetting(ctx context.Context, key string) (*AppSetting, error)
	GrantRole(ctx context.Context, arg GrantRoleParams) (*IdentityAccountRole, error)
	HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error)
	// 审计表只追加,应用层没有任何删除接口(见 docs/09-security.md 9.2)。
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (*IdentityAuditEvent, error)
	// 重发验证邮件时作废同用途的旧令牌。
	InvalidateEmailTokens(ctx context.Context, arg InvalidateEmailTokensParams) (int64, error)
	LinkSessionToSSO(ctx context.Context, arg LinkSessionToSSOParams) error
	// 权限求值的唯一入口:一次查完账号经角色持有的全部权限点。
	// 含通配符展开(如 mc:* → 匹配所有 minecraft:* 权限点)。
	ListAccountPermissions(ctx context.Context, accountID uuid.UUID) ([]string, error)
	ListAccountRoles(ctx context.Context, accountID uuid.UUID) ([]*IdentityRole, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]*IdentityAccount, error)
	ListActiveSessions(ctx context.Context, accountID uuid.UUID) ([]*IdentitySession, error)
	ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]*ListInvitationsRow, error)
	ListPermissions(ctx context.Context) ([]*IdentityPermission, error)
	ListRoleAccounts(ctx context.Context, roleID uuid.UUID) ([]*IdentityAccount, error)
	ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]*IdentityPermission, error)
	ListRoles(ctx context.Context, dollar_1 string) ([]*IdentityRole, error)
	ListSettings(ctx context.Context) ([]*AppSetting, error)
	// 登录失败计数 +1。达到阈值时同时写 locked_until。
	RecordFailedAttempt(ctx context.Context, arg RecordFailedAttemptParams) (*IdentityCredential, error)
	// 登录成功后清零。
	ResetFailedAttempts(ctx context.Context, arg ResetFailedAttemptsParams) (*IdentityCredential, error)
	// 改密码后调用:吊销该账号全部会话。
	RevokeAllSessions(ctx context.Context, arg RevokeAllSessionsParams) (int64, error)
	RevokeInvitation(ctx context.Context, id uuid.UUID) (int64, error)
	RevokeRole(ctx context.Context, arg RevokeRoleParams) (int64, error)
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (*IdentitySession, error)
	// 后台审计检索。account_id 为 NULL 时不按账号过滤。
	SearchAuditEvents(ctx context.Context, arg SearchAuditEventsParams) ([]*IdentityAuditEvent, error)
	SetAccountEmailVerified(ctx context.Context, id uuid.UUID) (*IdentityAccount, error)
	// mc_login_enabled 是通用布尔开关,内核不理解其业务语义(见迁移注释)。
	SetMCLoginEnabled(ctx context.Context, arg SetMCLoginEnabledParams) (*IdentityAccount, error)
	// 授权前先清空再写入,整体替换语义。
	SetRolePermissions(ctx context.Context, roleID uuid.UUID) error
	TouchCredentialChangedAt(ctx context.Context, arg TouchCredentialChangedAtParams) error
	// 滑动过期:只推进 idle_expires_at,绝不改 expires_at(绝对过期不因活跃而延长)。
	TouchSession(ctx context.Context, arg TouchSessionParams) (*IdentitySession, error)
	// 只改展示层字段。username_lower 由服务层保证同步更新。
	UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (*IdentityAccount, error)
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (*IdentityAccount, error)
	// is_system 的内置角色不允许改名改 code,避免破坏依赖角色 code 的脚本。
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (*IdentityRole, error)
	// 每账号每算法一条(UNIQUE(account_id, algo)),支持多算法并存迁移。
	UpsertCredential(ctx context.Context, arg UpsertCredentialParams) (*IdentityCredential, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (*AppSetting, error)
}

var _ Querier = (*Queries)(nil)
