// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO identity.role_permission (role_id, permission)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID     uuid.UUID `json:"role_id"`
	Permission string    `json:"permission"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.Permission)
	return err
}

const countAccountsWithRole = `-- name: CountAccountsWithRole :one
SELECT count(*) FROM identity.account_role WHERE role_id = $1
`

func (q *Queries) CountAccountsWithRole(ctx context.Context, roleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountsWithRole, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO identity.role (code, name, description, is_system)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, description, is_system, created_at, updated_at
`

type CreateRoleParams struct {
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsSystem    bool        `json:"is_system"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (*IdentityRole, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.IsSystem,
	)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM identity.role WHERE id = $1 AND is_system = FALSE
`

// 内置角色不可删。返回 0 行表示「角色不存在」或「是内置角色」,由服务层区分。
func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPermission = `-- name: GetPermission :one
SELECT code, description, created_at FROM identity.permission WHERE code = $1
`

func (q *Queries) GetPermission(ctx context.Context, code string) (*IdentityPermission, error) {
	row := q.db.QueryRow(ctx, getPermission, code)
	var i IdentityPermission
	err := row.Scan(&i.Code, &i.Description, &i.CreatedAt)
	return &i, err
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, code, name, description, is_system, created_at, updated_at FROM identity.role WHERE code = $1
`

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (*IdentityRole, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, code, name, description, is_system, created_at, updated_at FROM identity.role WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (*IdentityRole, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const grantRole = `-- name: GrantRole :one
INSERT INTO identity.account_role (account_id, role_id, granted_by)
VALUES ($1, $2, $3)
ON CONFLICT (account_id, role_id) DO UPDATE SET granted_by = EXCLUDED.granted_by
RETURNING account_id, role_id, granted_at, granted_by
`

type GrantRoleParams struct {
	AccountID uuid.UUID   `json:"account_id"`
	RoleID    uuid.UUID   `json:"role_id"`
	GrantedBy pgtype.UUID `json:"granted_by"`
}

func (q *Queries) GrantRole(ctx context.Context, arg GrantRoleParams) (*IdentityAccountRole, error) {
	row := q.db.QueryRow(ctx, grantRole, arg.AccountID, arg.RoleID, arg.GrantedBy)
	var i IdentityAccountRole
	err := row.Scan(
		&i.AccountID,
		&i.RoleID,
		&i.GrantedAt,
		&i.GrantedBy,
	)
	return &i, err
}

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS (
    SELECT 1 FROM identity.account_role ar
    JOIN identity.role_permission rp ON rp.role_id = ar.role_id
    WHERE ar.account_id = $1 AND rp.permission = $2
)
`

type HasPermissionParams struct {
	AccountID  uuid.UUID `json:"account_id"`
	Permission string    `json:"permission"`
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPermission, arg.AccountID, arg.Permission)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAccountPermissions = `-- name: ListAccountPermissions :many
SELECT DISTINCT p.code FROM identity.account_role ar
JOIN identity.role_permission rp ON rp.role_id = ar.role_id
JOIN identity.permission p ON p.code = rp.permission
WHERE ar.account_id = $1
ORDER BY p.code
`

// 权限求值的唯一入口:一次查完账号经角色持有的全部权限点。
// 含通配符展开(如 mc:* → 匹配所有 minecraft:* 权限点)。
func (q *Queries) ListAccountPermissions(ctx context.Context, accountID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAccountPermissions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountRoles = `-- name: ListAccountRoles :many
SELECT r.id, r.code, r.name, r.description, r.is_system, r.created_at, r.updated_at FROM identity.account_role ar
JOIN identity.role r ON r.id = ar.role_id
WHERE ar.account_id = $1
ORDER BY r.code
`

func (q *Queries) ListAccountRoles(ctx context.Context, accountID uuid.UUID) ([]*IdentityRole, error) {
	rows, err := q.db.Query(ctx, listAccountRoles, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*IdentityRole{}
	for rows.Next() {
		var i IdentityRole
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT code, description, created_at FROM identity.permission ORDER BY code
`

func (q *Queries) ListPermissions(ctx context.Context) ([]*IdentityPermission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*IdentityPermission{}
	for rows.Next() {
		var i IdentityPermission
		if err := rows.Scan(&i.Code, &i.Description, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleAccounts = `-- name: ListRoleAccounts :many
SELECT a.id, a.username, a.username_lower, a.email, a.status, a.mc_login_enabled, a.email_verified_at, a.created_at, a.updated_at FROM identity.account_role ar
JOIN identity.account a ON a.id = ar.account_id
WHERE ar.role_id = $1
ORDER BY a.created_at DESC
`

func (q *Queries) ListRoleAccounts(ctx context.Context, roleID uuid.UUID) ([]*IdentityAccount, error) {
	rows, err := q.db.Query(ctx, listRoleAccounts, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*IdentityAccount{}
	for rows.Next() {
		var i IdentityAccount
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.UsernameLower,
			&i.Email,
			&i.Status,
			&i.McLoginEnabled,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT p.code, p.description, p.created_at FROM identity.role_permission rp
JOIN identity.permission p ON p.code = rp.permission
WHERE rp.role_id = $1
ORDER BY p.code
`

func (q *Queries) ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]*IdentityPermission, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*IdentityPermission{}
	for rows.Next() {
		var i IdentityPermission
		if err := rows.Scan(&i.Code, &i.Description, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, code, name, description, is_system, created_at, updated_at FROM identity.role
WHERE ($1::text IS NULL OR code LIKE $1 OR name LIKE $1)
ORDER BY is_system DESC, code
`

func (q *Queries) ListRoles(ctx context.Context, dollar_1 string) ([]*IdentityRole, error) {
	rows, err := q.db.Query(ctx, listRoles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*IdentityRole{}
	for rows.Next() {
		var i IdentityRole
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRole = `-- name: RevokeRole :execrows
DELETE FROM identity.account_role WHERE account_id = $1 AND role_id = $2
`

type RevokeRoleParams struct {
	AccountID uuid.UUID `json:"account_id"`
	RoleID    uuid.UUID `json:"role_id"`
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRole, arg.AccountID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRolePermissions = `-- name: SetRolePermissions :exec
DELETE FROM identity.role_permission WHERE role_id = $1
`

// 授权前先清空再写入,整体替换语义。
func (q *Queries) SetRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setRolePermissions, roleID)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE identity.role
SET name = $2, description = $3
WHERE id = $1 AND is_system = FALSE
RETURNING id, code, name, description, is_system, created_at, updated_at
`

type UpdateRoleParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

// is_system 的内置角色不允许改名改 code,避免破坏依赖角色 code 的脚本。
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (*IdentityRole, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.ID, arg.Name, arg.Description)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
