// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package query

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSessions = `-- name: CountActiveSessions :one
SELECT count(*) FROM identity.session
WHERE account_id = $1 AND revoked_at IS NULL
  AND idle_expires_at > now() AND expires_at > now()
`

func (q *Queries) CountActiveSessions(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessions, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO identity.session (
    account_id, token_hash, sso_session_id, expires_at, idle_expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, account_id, token_hash, sso_session_id, created_at, last_seen_at, expires_at, idle_expires_at, revoked_at, revoke_reason, ip, user_agent
`

type CreateSessionParams struct {
	AccountID     uuid.UUID   `json:"account_id"`
	TokenHash     []byte      `json:"token_hash"`
	SsoSessionID  pgtype.UUID `json:"sso_session_id"`
	ExpiresAt     time.Time   `json:"expires_at"`
	IdleExpiresAt time.Time   `json:"idle_expires_at"`
	Ip            *netip.Addr `json:"ip"`
	UserAgent     pgtype.Text `json:"user_agent"`
}

// 只存 sha256(token),不存明文。
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (*IdentitySession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.AccountID,
		arg.TokenHash,
		arg.SsoSessionID,
		arg.ExpiresAt,
		arg.IdleExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i IdentitySession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.SsoSessionID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.Ip,
		&i.UserAgent,
	)
	return &i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM identity.session
WHERE (expires_at < now() - interval '30 days')
   OR (revoked_at IS NOT NULL AND revoked_at < now() - interval '30 days')
`

// 后台清理任务用:删除已过期或已吊销超过 30 天的会话。
func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT id, account_id, token_hash, sso_session_id, created_at, last_seen_at, expires_at, idle_expires_at, revoked_at, revoke_reason, ip, user_agent FROM identity.session
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND idle_expires_at > now()
  AND expires_at > now()
`

// 会话校验是最高频查询:只看未吊销、未过期的行。
func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, tokenHash []byte) (*IdentitySession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, tokenHash)
	var i IdentitySession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.SsoSessionID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.Ip,
		&i.UserAgent,
	)
	return &i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, account_id, token_hash, sso_session_id, created_at, last_seen_at, expires_at, idle_expires_at, revoked_at, revoke_reason, ip, user_agent FROM identity.session WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (*IdentitySession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i IdentitySession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.SsoSessionID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.Ip,
		&i.UserAgent,
	)
	return &i, err
}

const getSessionBySSOID = `-- name: GetSessionBySSOID :many
SELECT id, account_id, token_hash, sso_session_id, created_at, last_seen_at, expires_at, idle_expires_at, revoked_at, revoke_reason, ip, user_agent FROM identity.session
WHERE sso_session_id = $1 AND revoked_at IS NULL
`

// 全局登出:把同一 SSO 会话下的所有终端用户会话一起吊销。
func (q *Queries) GetSessionBySSOID(ctx context.Context, ssoSessionID pgtype.UUID) ([]*IdentitySession, error) {
	rows, err := q.db.Query(ctx, getSessionBySSOID, ssoSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*IdentitySession{}
	for rows.Next() {
		var i IdentitySession
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TokenHash,
			&i.SsoSessionID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.IdleExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.Ip,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkSessionToSSO = `-- name: LinkSessionToSSO :exec
UPDATE identity.session SET sso_session_id = $2 WHERE id = $1
`

type LinkSessionToSSOParams struct {
	ID           uuid.UUID   `json:"id"`
	SsoSessionID pgtype.UUID `json:"sso_session_id"`
}

func (q *Queries) LinkSessionToSSO(ctx context.Context, arg LinkSessionToSSOParams) error {
	_, err := q.db.Exec(ctx, linkSessionToSSO, arg.ID, arg.SsoSessionID)
	return err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, account_id, token_hash, sso_session_id, created_at, last_seen_at, expires_at, idle_expires_at, revoked_at, revoke_reason, ip, user_agent FROM identity.session
WHERE account_id = $1
  AND revoked_at IS NULL
  AND idle_expires_at > now()
  AND expires_at > now()
ORDER BY last_seen_at DESC
`

func (q *Queries) ListActiveSessions(ctx context.Context, accountID uuid.UUID) ([]*IdentitySession, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*IdentitySession{}
	for rows.Next() {
		var i IdentitySession
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TokenHash,
			&i.SsoSessionID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.IdleExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.Ip,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessions = `-- name: RevokeAllSessions :execrows
UPDATE identity.session SET revoked_at = now(), revoke_reason = $2
WHERE account_id = $1 AND revoked_at IS NULL
`

type RevokeAllSessionsParams struct {
	AccountID    uuid.UUID   `json:"account_id"`
	RevokeReason pgtype.Text `json:"revoke_reason"`
}

// 改密码后调用:吊销该账号全部会话。
func (q *Queries) RevokeAllSessions(ctx context.Context, arg RevokeAllSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllSessions, arg.AccountID, arg.RevokeReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :one
UPDATE identity.session
SET revoked_at = now(), revoke_reason = $2
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, account_id, token_hash, sso_session_id, created_at, last_seen_at, expires_at, idle_expires_at, revoked_at, revoke_reason, ip, user_agent
`

type RevokeSessionParams struct {
	ID           uuid.UUID   `json:"id"`
	RevokeReason pgtype.Text `json:"revoke_reason"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (*IdentitySession, error) {
	row := q.db.QueryRow(ctx, revokeSession, arg.ID, arg.RevokeReason)
	var i IdentitySession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.SsoSessionID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.Ip,
		&i.UserAgent,
	)
	return &i, err
}

const touchSession = `-- name: TouchSession :one
UPDATE identity.session SET last_seen_at = now(), idle_expires_at = $2
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, account_id, token_hash, sso_session_id, created_at, last_seen_at, expires_at, idle_expires_at, revoked_at, revoke_reason, ip, user_agent
`

type TouchSessionParams struct {
	ID            uuid.UUID `json:"id"`
	IdleExpiresAt time.Time `json:"idle_expires_at"`
}

// 滑动过期:只推进 idle_expires_at,绝不改 expires_at(绝对过期不因活跃而延长)。
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (*IdentitySession, error) {
	row := q.db.QueryRow(ctx, touchSession, arg.ID, arg.IdleExpiresAt)
	var i IdentitySession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.SsoSessionID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.Ip,
		&i.UserAgent,
	)
	return &i, err
}
