// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setting.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSetting = `-- name: DeleteSetting :execrows
DELETE FROM app.setting WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSetting, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSetting = `-- name: GetSetting :one
SELECT key, value, updated_at, updated_by FROM app.setting WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (*AppSetting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return &i, err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, updated_at, updated_by FROM app.setting ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]*AppSetting, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AppSetting{}
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO app.setting (key, value, updated_by)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING key, value, updated_at, updated_by
`

type UpsertSettingParams struct {
	Key       string      `json:"key"`
	Value     []byte      `json:"value"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (*AppSetting, error) {
	row := q.db.QueryRow(ctx, upsertSetting, arg.Key, arg.Value, arg.UpdatedBy)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return &i, err
}
